import type { VisitorUiText } from "./visitor-localization.js";
import type { OperatorStatus } from "./types.js";

export const EXTENDED_VISITOR_UI_TEXT: Record<string, VisitorUiText> = {
  be: {
    selectLanguageTitle: "Выберыце сваю мову",
    selectLanguageDescription: "Націсніце мову, якую хочаце чытаць і выкарыстоўваць на гэтым экране.",
    whatYouSay: "Што вы кажаце",
    whatYouSayHint: "Ваша гаворка будзе паказвацца тут, пакуль вы ўтрымліваеце кнопку.",
    operatorTranslation: "Пераклад аператара",
    operatorTranslationHint: "Перакладзены адказ аператара будзе паказвацца тут.",
    conversationHistory: "Гісторыя размовы",
    conversationHistoryHint: "Пацверджаныя рэплікі бягучай сесіі будуць паказвацца тут.",
    sessionContext: "Кантэкст сесіі",
    sessionTurns: (count) => `${count} ходаў`,
    holdToSpeak: "Утрымлівайце, каб гаварыць",
    pressAndSpeak: "Націсніце і гаварыце",
    waitingAvailability: "Чаканне гатоўнасці",
    changeLanguage: "Змяніць мову",
    closeSession: "Закрыць сесію",
    currentLanguage: "Мова",
    confirmCloseSession: "Закрыць бягучую сесію",
    confirmCloseSessionDescription: "Бягучая размова будзе ачышчана на абодвух экранах.",
    cancel: "Адмена",
    confirm: "Пацвердзіць",
  },
  bg: {
    selectLanguageTitle: "Изберете своя език",
    selectLanguageDescription: "Докоснете езика, който искате да четете и използвате на този екран.",
    whatYouSay: "Какво казвате",
    whatYouSayHint: "Речта ви ще се показва тук, докато държите бутона натиснат.",
    operatorTranslation: "Превод на оператора",
    operatorTranslationHint: "Преведеният отговор на оператора ще се показва тук.",
    conversationHistory: "История на разговора",
    conversationHistoryHint: "Потвърдените реплики от текущата сесия ще се показват тук.",
    sessionContext: "Контекст на сесията",
    sessionTurns: (count) => `${count} хода`,
    holdToSpeak: "Задръжте, за да говорите",
    pressAndSpeak: "Натиснете и говорете",
    waitingAvailability: "Изчакване на готовност",
    changeLanguage: "Смяна на езика",
    closeSession: "Затвори сесията",
    currentLanguage: "Език",
    confirmCloseSession: "Затвори текущата сесия",
    confirmCloseSessionDescription: "Текущият разговор ще бъде изчистен и на двата екрана.",
    cancel: "Отказ",
    confirm: "Потвърди",
  },
  bs: {
    selectLanguageTitle: "Odaberite svoj jezik",
    selectLanguageDescription: "Dodirnite jezik koji želite čitati i koristiti na ovom ekranu.",
    whatYouSay: "Šta govorite",
    whatYouSayHint: "Vaš govor će se pojaviti ovdje dok držite dugme pritisnuto.",
    operatorTranslation: "Prijevod operatera",
    operatorTranslationHint: "Prevedeni odgovor operatera će se pojaviti ovdje.",
    conversationHistory: "Historija razgovora",
    conversationHistoryHint: "Potvrđene razmjene iz trenutne sesije pojavit će se ovdje.",
    sessionContext: "Kontekst sesije",
    sessionTurns: (count) => `${count} razmjena`,
    holdToSpeak: "Držite za govor",
    pressAndSpeak: "Pritisnite i govorite",
    waitingAvailability: "Čeka se spremnost",
    changeLanguage: "Promijeni jezik",
    closeSession: "Zatvori sesiju",
    currentLanguage: "Jezik",
    confirmCloseSession: "Zatvori trenutnu sesiju",
    confirmCloseSessionDescription: "Trenutni razgovor će biti obrisan na oba ekrana.",
    cancel: "Otkaži",
    confirm: "Potvrdi",
  },
  ca: {
    selectLanguageTitle: "Trieu la vostra llengua",
    selectLanguageDescription: "Toqueu la llengua que voleu llegir i utilitzar en aquesta pantalla.",
    whatYouSay: "Allò que dieu",
    whatYouSayHint: "La vostra veu apareixerà aquí mentre manteniu el botó premut.",
    operatorTranslation: "Traducció de l'operador",
    operatorTranslationHint: "La resposta traduïda de l'operador apareixerà aquí.",
    conversationHistory: "Historial de conversa",
    conversationHistoryHint: "Els torns confirmats de la sessió actual apareixeran aquí.",
    sessionContext: "Context de la sessió",
    sessionTurns: (count) => `${count} torns`,
    holdToSpeak: "Manteniu premut per parlar",
    pressAndSpeak: "Premeu i parleu",
    waitingAvailability: "Esperant disponibilitat",
    changeLanguage: "Canvia la llengua",
    closeSession: "Tanca la sessió",
    currentLanguage: "Llengua",
    confirmCloseSession: "Tanca la sessió actual",
    confirmCloseSessionDescription: "La conversa actual s'esborrarà a les dues pantalles.",
    cancel: "Cancel·la",
    confirm: "Confirma",
  },
  cs: {
    selectLanguageTitle: "Vyberte si svůj jazyk",
    selectLanguageDescription: "Klepněte na jazyk, který chcete na této obrazovce číst a používat.",
    whatYouSay: "Co říkáte",
    whatYouSayHint: "Vaše řeč se zde zobrazí, dokud držíte tlačítko stisknuté.",
    operatorTranslation: "Překlad operátora",
    operatorTranslationHint: "Přeložená odpověď operátora se zobrazí zde.",
    conversationHistory: "Historie konverzace",
    conversationHistoryHint: "Zde se zobrazí potvrzené tahy aktuální relace.",
    sessionContext: "Kontext relace",
    sessionTurns: (count) => `${count} tahů`,
    holdToSpeak: "Podržte pro mluvení",
    pressAndSpeak: "Stiskněte a mluvte",
    waitingAvailability: "Čeká se na připravenost",
    changeLanguage: "Změnit jazyk",
    closeSession: "Ukončit relaci",
    currentLanguage: "Jazyk",
    confirmCloseSession: "Ukončit aktuální relaci",
    confirmCloseSessionDescription: "Aktuální konverzace bude vymazána na obou obrazovkách.",
    cancel: "Zrušit",
    confirm: "Potvrdit",
  },
  cy: {
    selectLanguageTitle: "Dewiswch eich iaith",
    selectLanguageDescription: "Cyffyrddwch â'r iaith rydych am ei darllen a'i defnyddio ar y sgrin hon.",
    whatYouSay: "Beth rydych yn ei ddweud",
    whatYouSayHint: "Bydd eich llais yn ymddangos yma tra byddwch yn dal y botwm i lawr.",
    operatorTranslation: "Cyfieithiad y gweithredwr",
    operatorTranslationHint: "Bydd ateb wedi'i gyfieithu'r gweithredwr yn ymddangos yma.",
    conversationHistory: "Hanes y sgwrs",
    conversationHistoryHint: "Bydd troeon wedi'u cadarnhau'r sesiwn gyfredol yn ymddangos yma.",
    sessionContext: "Cyd-destun y sesiwn",
    sessionTurns: (count) => `${count} tro`,
    holdToSpeak: "Daliwch i siarad",
    pressAndSpeak: "Pwyswch a siaradwch",
    waitingAvailability: "Yn aros am barodrwydd",
    changeLanguage: "Newid iaith",
    closeSession: "Cau'r sesiwn",
    currentLanguage: "Iaith",
    confirmCloseSession: "Cau'r sesiwn gyfredol",
    confirmCloseSessionDescription: "Bydd y sgwrs gyfredol yn cael ei chlirio ar y ddwy sgrin.",
    cancel: "Canslo",
    confirm: "Cadarnhau",
  },
  da: {
    selectLanguageTitle: "Vælg dit sprog",
    selectLanguageDescription: "Tryk på det sprog, du vil læse og bruge på denne skærm.",
    whatYouSay: "Det du siger",
    whatYouSayHint: "Din tale vises her, mens du holder knappen nede.",
    operatorTranslation: "Operatørens oversættelse",
    operatorTranslationHint: "Operatørens oversatte svar vises her.",
    conversationHistory: "Samtalehistorik",
    conversationHistoryHint: "Bekræftede ture fra den aktuelle session vises her.",
    sessionContext: "Sessionskontekst",
    sessionTurns: (count) => `${count} ture`,
    holdToSpeak: "Hold nede for at tale",
    pressAndSpeak: "Tryk og tal",
    waitingAvailability: "Venter på klar status",
    changeLanguage: "Skift sprog",
    closeSession: "Luk session",
    currentLanguage: "Sprog",
    confirmCloseSession: "Luk den aktuelle session",
    confirmCloseSessionDescription: "Den aktuelle samtale ryddes på begge skærme.",
    cancel: "Annuller",
    confirm: "Bekræft",
  },
  et: {
    selectLanguageTitle: "Valige oma keel",
    selectLanguageDescription: "Puudutage keelt, mida soovite sellel ekraanil lugeda ja kasutada.",
    whatYouSay: "Mida te ütlete",
    whatYouSayHint: "Teie kõne kuvatakse siin seni, kuni hoiate nuppu all.",
    operatorTranslation: "Operaatori tõlge",
    operatorTranslationHint: "Operaatori tõlgitud vastus kuvatakse siin.",
    conversationHistory: "Vestluse ajalugu",
    conversationHistoryHint: "Siin kuvatakse käesoleva seansi kinnitatud vahetused.",
    sessionContext: "Seansi kontekst",
    sessionTurns: (count) => `${count} vooru`,
    holdToSpeak: "Rääkimiseks hoidke all",
    pressAndSpeak: "Vajutage ja rääkige",
    waitingAvailability: "Valmisoleku ootamine",
    changeLanguage: "Muuda keelt",
    closeSession: "Sulge seanss",
    currentLanguage: "Keel",
    confirmCloseSession: "Sulge praegune seanss",
    confirmCloseSessionDescription: "Praegune vestlus kustutatakse mõlemalt ekraanilt.",
    cancel: "Tühista",
    confirm: "Kinnita",
  },
  fi: {
    selectLanguageTitle: "Valitse kielesi",
    selectLanguageDescription: "Napauta kieltä, jota haluat lukea ja käyttää tällä näytöllä.",
    whatYouSay: "Mitä sanot",
    whatYouSayHint: "Puheesi näkyy täällä, kun pidät painiketta painettuna.",
    operatorTranslation: "Operaattorin käännös",
    operatorTranslationHint: "Operaattorin käännetty vastaus näkyy täällä.",
    conversationHistory: "Keskusteluhistoria",
    conversationHistoryHint: "Nykyisen istunnon vahvistetut vuorot näkyvät täällä.",
    sessionContext: "Istunnon konteksti",
    sessionTurns: (count) => `${count} vuoroa`,
    holdToSpeak: "Pidä pohjassa puhuaksesi",
    pressAndSpeak: "Paina ja puhu",
    waitingAvailability: "Odotetaan valmiutta",
    changeLanguage: "Vaihda kieli",
    closeSession: "Sulje istunto",
    currentLanguage: "Kieli",
    confirmCloseSession: "Sulje nykyinen istunto",
    confirmCloseSessionDescription: "Nykyinen keskustelu tyhjennetään molemmilta näytöiltä.",
    cancel: "Peruuta",
    confirm: "Vahvista",
  },
  ga: {
    selectLanguageTitle: "Roghnaigh do theanga",
    selectLanguageDescription: "Tapáil an teanga is mian leat a léamh agus a úsáid ar an scáileán seo.",
    whatYouSay: "An méid a deir tú",
    whatYouSayHint: "Beidh do chuid cainte le feiceáil anseo agus an cnaipe á choinneáil síos agat.",
    operatorTranslation: "Aistriúchán an oibreora",
    operatorTranslationHint: "Beidh freagra aistrithe an oibreora le feiceáil anseo.",
    conversationHistory: "Stair an chomhrá",
    conversationHistoryHint: "Beidh sealanna deimhnithe an tseisiúin reatha le feiceáil anseo.",
    sessionContext: "Comhthéacs an tseisiúin",
    sessionTurns: (count) => `${count} seal`,
    holdToSpeak: "Coinnigh síos chun labhairt",
    pressAndSpeak: "Brúigh agus labhair",
    waitingAvailability: "Ag fanacht le bheith réidh",
    changeLanguage: "Athraigh teanga",
    closeSession: "Dún an seisiún",
    currentLanguage: "Teanga",
    confirmCloseSession: "Dún an seisiún reatha",
    confirmCloseSessionDescription: "Glanfar an comhrá reatha ar an dá scáileán.",
    cancel: "Cealaigh",
    confirm: "Deimhnigh",
  },
  hr: {
    selectLanguageTitle: "Odaberite svoj jezik",
    selectLanguageDescription: "Dodirnite jezik koji želite čitati i koristiti na ovom zaslonu.",
    whatYouSay: "Što govorite",
    whatYouSayHint: "Vaš govor će se pojaviti ovdje dok držite tipku pritisnutom.",
    operatorTranslation: "Prijevod operatera",
    operatorTranslationHint: "Prevedeni odgovor operatera pojavit će se ovdje.",
    conversationHistory: "Povijest razgovora",
    conversationHistoryHint: "Ovdje će se prikazati potvrđene razmjene trenutačne sesije.",
    sessionContext: "Kontekst sesije",
    sessionTurns: (count) => `${count} razmjena`,
    holdToSpeak: "Držite za govor",
    pressAndSpeak: "Pritisnite i govorite",
    waitingAvailability: "Čeka se spremnost",
    changeLanguage: "Promijeni jezik",
    closeSession: "Zatvori sesiju",
    currentLanguage: "Jezik",
    confirmCloseSession: "Zatvori trenutačnu sesiju",
    confirmCloseSessionDescription: "Trenutačni razgovor bit će obrisan na oba zaslona.",
    cancel: "Odustani",
    confirm: "Potvrdi",
  },
  is: {
    selectLanguageTitle: "Veldu tungumálið þitt",
    selectLanguageDescription: "Pikkaðu á tungumálið sem þú vilt lesa og nota á þessum skjá.",
    whatYouSay: "Það sem þú segir",
    whatYouSayHint: "Tal þitt birtist hér meðan þú heldur hnappinum niðri.",
    operatorTranslation: "Þýðing starfsmanns",
    operatorTranslationHint: "Þýtt svar starfsmanns birtist hér.",
    conversationHistory: "Samtalasaga",
    conversationHistoryHint: "Staðfest umferðir úr núverandi lotu birtast hér.",
    sessionContext: "Samhengi lotu",
    sessionTurns: (count) => `${count} umferðir`,
    holdToSpeak: "Haltu inni til að tala",
    pressAndSpeak: "Ýttu og talaðu",
    waitingAvailability: "Bíður eftir að vera tilbúið",
    changeLanguage: "Skipta um tungumál",
    closeSession: "Loka lotu",
    currentLanguage: "Tungumál",
    confirmCloseSession: "Loka núverandi lotu",
    confirmCloseSessionDescription: "Núverandi samtal verður hreinsað á báðum skjám.",
    cancel: "Hætta við",
    confirm: "Staðfesta",
  },
  lt: {
    selectLanguageTitle: "Pasirinkite savo kalbą",
    selectLanguageDescription: "Palieskite kalbą, kurią norite skaityti ir naudoti šiame ekrane.",
    whatYouSay: "Ką sakote",
    whatYouSayHint: "Jūsų kalba bus rodoma čia, kol laikysite mygtuką nuspaustą.",
    operatorTranslation: "Operatoriaus vertimas",
    operatorTranslationHint: "Čia bus rodoma išversta operatoriaus žinutė.",
    conversationHistory: "Pokalbio istorija",
    conversationHistoryHint: "Čia bus rodomi patvirtinti dabartinės sesijos pasikeitimai.",
    sessionContext: "Sesijos kontekstas",
    sessionTurns: (count) => `${count} ėjimai`,
    holdToSpeak: "Laikykite nuspaudę, kad kalbėtumėte",
    pressAndSpeak: "Paspauskite ir kalbėkite",
    waitingAvailability: "Laukiama pasirengimo",
    changeLanguage: "Keisti kalbą",
    closeSession: "Uždaryti sesiją",
    currentLanguage: "Kalba",
    confirmCloseSession: "Uždaryti dabartinę sesiją",
    confirmCloseSessionDescription: "Dabartinis pokalbis bus išvalytas abiejuose ekranuose.",
    cancel: "Atšaukti",
    confirm: "Patvirtinti",
  },
  lv: {
    selectLanguageTitle: "Izvēlieties savu valodu",
    selectLanguageDescription: "Pieskarieties valodai, kuru vēlaties lasīt un izmantot šajā ekrānā.",
    whatYouSay: "Ko jūs sakāt",
    whatYouSayHint: "Jūsu runa tiks rādīta šeit, kamēr turēsiet pogu nospiestu.",
    operatorTranslation: "Operatora tulkojums",
    operatorTranslationHint: "Šeit tiks rādīta operatora tulkotā atbilde.",
    conversationHistory: "Sarunas vēsture",
    conversationHistoryHint: "Šeit tiks rādīti apstiprinātie pašreizējās sesijas gājieni.",
    sessionContext: "Sesijas konteksts",
    sessionTurns: (count) => `${count} gājieni`,
    holdToSpeak: "Turiet nospiestu, lai runātu",
    pressAndSpeak: "Nospiediet un runājiet",
    waitingAvailability: "Gaida gatavību",
    changeLanguage: "Mainīt valodu",
    closeSession: "Aizvērt sesiju",
    currentLanguage: "Valoda",
    confirmCloseSession: "Aizvērt pašreizējo sesiju",
    confirmCloseSessionDescription: "Pašreizējā saruna tiks notīrīta abos ekrānos.",
    cancel: "Atcelt",
    confirm: "Apstiprināt",
  },
  mt: {
    selectLanguageTitle: "Agħżel il-lingwa tiegħek",
    selectLanguageDescription: "Mess il-lingwa li trid taqra u tuża fuq dan l-iskrin.",
    whatYouSay: "Dak li tgħid",
    whatYouSayHint: "Il-kliem tiegħek jidher hawn waqt li żżomm il-buttuna magħfusa.",
    operatorTranslation: "Traduzzjoni tal-operatur",
    operatorTranslationHint: "Ir-risposta tradotta tal-operatur tidher hawn.",
    conversationHistory: "Storja tal-konversazzjoni",
    conversationHistoryHint: "It-turns ikkonfermati tas-sessjoni kurrenti jidhru hawn.",
    sessionContext: "Kuntest tas-sessjoni",
    sessionTurns: (count) => `${count} turns`,
    holdToSpeak: "Żomm magħfus biex titkellem",
    pressAndSpeak: "Agħfas u tkellem",
    waitingAvailability: "Qed jistenna li jkun lest",
    changeLanguage: "Ibdel il-lingwa",
    closeSession: "Agħlaq is-sessjoni",
    currentLanguage: "Lingwa",
    confirmCloseSession: "Agħlaq is-sessjoni kurrenti",
    confirmCloseSessionDescription: "Il-konversazzjoni kurrenti titħassar fuq iż-żewġ skrins.",
    cancel: "Ikkanċella",
    confirm: "Ikkonferma",
  },
  mi: {
    selectLanguageTitle: "Kōwhiria tō reo",
    selectLanguageDescription: "Pāwhiritia te reo e hiahia ana koe ki te pānui me te whakamahi i tēnei mata.",
    whatYouSay: "Āu kōrero",
    whatYouSayHint: "Ka whakaaturia tō reo ki konei i a koe e pupuri ana i te pātene.",
    operatorTranslation: "Whakamāoritanga a te kaiwhakahaere",
    operatorTranslationHint: "Ka whakaaturia te whakahoki kua whakamāoritia a te kaiwhakahaere ki konei.",
    conversationHistory: "Hītori kōrero",
    conversationHistoryHint: "Ka whakaaturia ngā huringa kua whakamanatia o te wātū o nāianei ki konei.",
    sessionContext: "Horopaki wātū",
    sessionTurns: (count) => `${count} huringa`,
    holdToSpeak: "Pupuri kia kōrero",
    pressAndSpeak: "Pēhi ka kōrero",
    waitingAvailability: "E tatari ana kia wātea",
    changeLanguage: "Huri reo",
    closeSession: "Katia te wātū",
    currentLanguage: "Reo",
    confirmCloseSession: "Katia te wātū o nāianei",
    confirmCloseSessionDescription: "Ka whakawāteatia te kōrerorero o nāianei i ngā mata e rua.",
    cancel: "Whakakore",
    confirm: "Whakaū",
  },
  nb: {
    selectLanguageTitle: "Velg språket ditt",
    selectLanguageDescription: "Trykk på språket du vil lese og bruke på denne skjermen.",
    whatYouSay: "Det du sier",
    whatYouSayHint: "Talen din vises her mens du holder knappen nede.",
    operatorTranslation: "Operatørens oversettelse",
    operatorTranslationHint: "Operatørens oversatte svar vises her.",
    conversationHistory: "Samtalehistorikk",
    conversationHistoryHint: "Bekreftede turer fra gjeldende økt vises her.",
    sessionContext: "Øktkontekst",
    sessionTurns: (count) => `${count} turer`,
    holdToSpeak: "Hold inne for å snakke",
    pressAndSpeak: "Trykk og snakk",
    waitingAvailability: "Venter på klarstatus",
    changeLanguage: "Bytt språk",
    closeSession: "Lukk økten",
    currentLanguage: "Språk",
    confirmCloseSession: "Lukk gjeldende økt",
    confirmCloseSessionDescription: "Den gjeldende samtalen blir tømt på begge skjermene.",
    cancel: "Avbryt",
    confirm: "Bekreft",
  },
  sk: {
    selectLanguageTitle: "Vyberte si svoj jazyk",
    selectLanguageDescription: "Ťuknite na jazyk, ktorý chcete na tejto obrazovke čítať a používať.",
    whatYouSay: "Čo hovoríte",
    whatYouSayHint: "Vaša reč sa zobrazí tu, kým držíte tlačidlo stlačené.",
    operatorTranslation: "Preklad operátora",
    operatorTranslationHint: "Preložená odpoveď operátora sa zobrazí tu.",
    conversationHistory: "História konverzácie",
    conversationHistoryHint: "Tu sa zobrazia potvrdené výmeny aktuálnej relácie.",
    sessionContext: "Kontext relácie",
    sessionTurns: (count) => `${count} výmen`,
    holdToSpeak: "Podržte pre hovorenie",
    pressAndSpeak: "Stlačte a hovorte",
    waitingAvailability: "Čaká sa na pripravenosť",
    changeLanguage: "Zmeniť jazyk",
    closeSession: "Ukončiť reláciu",
    currentLanguage: "Jazyk",
    confirmCloseSession: "Ukončiť aktuálnu reláciu",
    confirmCloseSessionDescription: "Aktuálna konverzácia sa vymaže na oboch obrazovkách.",
    cancel: "Zrušiť",
    confirm: "Potvrdiť",
  },
  sq: {
    selectLanguageTitle: "Zgjidhni gjuhën tuaj",
    selectLanguageDescription: "Prekni gjuhën që dëshironi të lexoni dhe të përdorni në këtë ekran.",
    whatYouSay: "Çfarë thoni",
    whatYouSayHint: "Fjala juaj do të shfaqet këtu ndërsa mbani butonin të shtypur.",
    operatorTranslation: "Përkthimi i operatorit",
    operatorTranslationHint: "Përgjigjja e përkthyer e operatorit do të shfaqet këtu.",
    conversationHistory: "Historiku i bisedës",
    conversationHistoryHint: "Këtu do të shfaqen kthesat e konfirmuara të sesionit aktual.",
    sessionContext: "Konteksti i sesionit",
    sessionTurns: (count) => `${count} kthesa`,
    holdToSpeak: "Mbajeni shtypur për të folur",
    pressAndSpeak: "Shtypni dhe flisni",
    waitingAvailability: "Në pritje të gatishmërisë",
    changeLanguage: "Ndrysho gjuhën",
    closeSession: "Mbyll sesionin",
    currentLanguage: "Gjuha",
    confirmCloseSession: "Mbyll sesionin aktual",
    confirmCloseSessionDescription: "Biseda aktuale do të pastrohet në të dy ekranet.",
    cancel: "Anulo",
    confirm: "Konfirmo",
  },
  "sr-Cyrl": {
    selectLanguageTitle: "Изаберите свој језик",
    selectLanguageDescription: "Додирните језик који желите да читате и користите на овом екрану.",
    whatYouSay: "Оно што говорите",
    whatYouSayHint: "Ваш говор ће се појавити овде док држите дугме притиснуто.",
    operatorTranslation: "Превод оператера",
    operatorTranslationHint: "Преведени одговор оператера ће се појавити овде.",
    conversationHistory: "Историја разговора",
    conversationHistoryHint: "Потврђене размене из текуће сесије појавиће се овде.",
    sessionContext: "Контекст сесије",
    sessionTurns: (count) => `${count} размена`,
    holdToSpeak: "Држите да бисте говорили",
    pressAndSpeak: "Притисните и говорите",
    waitingAvailability: "Чека се спремност",
    changeLanguage: "Промени језик",
    closeSession: "Затвори сесију",
    currentLanguage: "Језик",
    confirmCloseSession: "Затвори тренутну сесију",
    confirmCloseSessionDescription: "Тренутни разговор ће бити обрисан на оба екрана.",
    cancel: "Откажи",
    confirm: "Потврди",
  },
  "sr-Latn": {
    selectLanguageTitle: "Izaberite svoj jezik",
    selectLanguageDescription: "Dodirnite jezik koji želite da čitate i koristite na ovom ekranu.",
    whatYouSay: "Ono što govorite",
    whatYouSayHint: "Vaš govor će se pojaviti ovde dok držite dugme pritisnuto.",
    operatorTranslation: "Prevod operatera",
    operatorTranslationHint: "Prevedeni odgovor operatera će se pojaviti ovde.",
    conversationHistory: "Istorija razgovora",
    conversationHistoryHint: "Potvrđene razmene iz tekuće sesije pojaviće se ovde.",
    sessionContext: "Kontekst sesije",
    sessionTurns: (count) => `${count} razmena`,
    holdToSpeak: "Držite da biste govorili",
    pressAndSpeak: "Pritisnite i govorite",
    waitingAvailability: "Čeka se spremnost",
    changeLanguage: "Promeni jezik",
    closeSession: "Zatvori sesiju",
    currentLanguage: "Jezik",
    confirmCloseSession: "Zatvori trenutnu sesiju",
    confirmCloseSessionDescription: "Trenutni razgovor će biti obrisan na oba ekrana.",
    cancel: "Otkaži",
    confirm: "Potvrdi",
  },
  sl: {
    selectLanguageTitle: "Izberite svoj jezik",
    selectLanguageDescription: "Dotaknite se jezika, ki ga želite brati in uporabljati na tem zaslonu.",
    whatYouSay: "Kar govorite",
    whatYouSayHint: "Vaš govor se bo prikazal tukaj, dokler držite gumb pritisnjen.",
    operatorTranslation: "Prevod operaterja",
    operatorTranslationHint: "Preveden odgovor operaterja se bo prikazal tukaj.",
    conversationHistory: "Zgodovina pogovora",
    conversationHistoryHint: "Tukaj se bodo prikazale potrjene izmenjave trenutne seje.",
    sessionContext: "Kontekst seje",
    sessionTurns: (count) => `${count} izmenjav`,
    holdToSpeak: "Držite za govor",
    pressAndSpeak: "Pritisnite in govorite",
    waitingAvailability: "Čakanje na pripravljenost",
    changeLanguage: "Spremeni jezik",
    closeSession: "Zapri sejo",
    currentLanguage: "Jezik",
    confirmCloseSession: "Zapri trenutno sejo",
    confirmCloseSessionDescription: "Trenutni pogovor bo izbrisan na obeh zaslonih.",
    cancel: "Prekliči",
    confirm: "Potrdi",
  },
  sv: {
    selectLanguageTitle: "Välj ditt språk",
    selectLanguageDescription: "Tryck på språket som du vill läsa och använda på den här skärmen.",
    whatYouSay: "Det du säger",
    whatYouSayHint: "Ditt tal visas här medan du håller knappen nedtryckt.",
    operatorTranslation: "Operatörens översättning",
    operatorTranslationHint: "Operatörens översatta svar visas här.",
    conversationHistory: "Samtalshistorik",
    conversationHistoryHint: "Bekräftade turer från den aktuella sessionen visas här.",
    sessionContext: "Sessionskontext",
    sessionTurns: (count) => `${count} turer`,
    holdToSpeak: "Håll in för att tala",
    pressAndSpeak: "Tryck och tala",
    waitingAvailability: "Väntar på tillgänglighet",
    changeLanguage: "Byt språk",
    closeSession: "Stäng sessionen",
    currentLanguage: "Språk",
    confirmCloseSession: "Stäng den aktuella sessionen",
    confirmCloseSessionDescription: "Det aktuella samtalet rensas på båda skärmarna.",
    cancel: "Avbryt",
    confirm: "Bekräfta",
  },
  hu: {
    selectLanguageTitle: "Válassza ki a nyelvét",
    selectLanguageDescription: "Érintse meg azt a nyelvet, amelyet ezen a képernyőn olvasni és használni szeretne.",
    whatYouSay: "Amit mond",
    whatYouSayHint: "A beszéde itt jelenik meg, amíg nyomva tartja a gombot.",
    operatorTranslation: "A kezelő fordítása",
    operatorTranslationHint: "A kezelő lefordított válasza itt jelenik meg.",
    conversationHistory: "Beszélgetési előzmények",
    conversationHistoryHint: "Az aktuális munkamenet megerősített váltásai itt jelennek meg.",
    sessionContext: "Munkamenet környezet",
    sessionTurns: (count) => `${count} váltás`,
    holdToSpeak: "Tartsa lenyomva a beszédhez",
    pressAndSpeak: "Nyomja meg és beszéljen",
    waitingAvailability: "Elérhetőségre vár",
    changeLanguage: "Nyelv módosítása",
    closeSession: "Munkamenet bezárása",
    currentLanguage: "Nyelv",
    confirmCloseSession: "Az aktuális munkamenet bezárása",
    confirmCloseSessionDescription: "Az aktuális beszélgetés mindkét képernyőn törlődik.",
    cancel: "Mégse",
    confirm: "Megerősítés",
  },
  hy: {
    selectLanguageTitle: "Ընտրեք ձեր լեզուն",
    selectLanguageDescription: "Հպեք այն լեզվին, որը ցանկանում եք կարդալ և օգտագործել այս էկրանին։",
    whatYouSay: "Ինչ եք ասում",
    whatYouSayHint: "Ձեր խոսքը կհայտնվի այստեղ, քանի դեռ պահում եք կոճակը սեղմված։",
    operatorTranslation: "Օպերատորի թարգմանությունը",
    operatorTranslationHint: "Օպերատորի թարգմանված պատասխանը կհայտնվի այստեղ։",
    conversationHistory: "Զրույցի պատմություն",
    conversationHistoryHint: "Այստեղ կհայտնվեն ընթացիկ սեսիայի հաստատված հերթափոխերը։",
    sessionContext: "Սեսիայի համատեքստ",
    sessionTurns: (count) => `${count} հերթափոխ`,
    holdToSpeak: "Սեղմած պահեք՝ խոսելու համար",
    pressAndSpeak: "Սեղմեք և խոսեք",
    waitingAvailability: "Սպասում է հասանելիությանը",
    changeLanguage: "Փոխել լեզուն",
    closeSession: "Փակել սեսիան",
    currentLanguage: "Լեզու",
    confirmCloseSession: "Փակել ընթացիկ սեսիան",
    confirmCloseSessionDescription: "Ընթացիկ խոսակցությունը կմաքրվի երկու էկրաններից։",
    cancel: "Չեղարկել",
    confirm: "Հաստատել",
  },
  az: {
    selectLanguageTitle: "Dil seçin",
    selectLanguageDescription: "Bu ekranda oxumaq və istifadə etmək istədiyiniz dili seçin.",
    whatYouSay: "Dedikləriniz",
    whatYouSayHint: "Düyməni basılı saxladığınız müddətdə danışığınız burada görünəcək.",
    operatorTranslation: "Operator tərcüməsi",
    operatorTranslationHint: "Operatorun tərcümə olunmuş cavabı burada görünəcək.",
    conversationHistory: "Söhbət tarixçəsi",
    conversationHistoryHint: "Cari sessiyanın təsdiqlənmiş növbələri burada görünəcək.",
    sessionContext: "Sessiya konteksti",
    sessionTurns: (count) => `${count} növbə`,
    holdToSpeak: "Danışmaq üçün basıb saxlayın",
    pressAndSpeak: "Basın və danışın",
    waitingAvailability: "Hazırlığı gözləyir",
    changeLanguage: "Dili dəyiş",
    closeSession: "Sessiyanı bağla",
    currentLanguage: "Dil",
    confirmCloseSession: "Cari sessiyanı bağla",
    confirmCloseSessionDescription: "Cari danışıq hər iki ekranda silinəcək.",
    cancel: "Ləğv et",
    confirm: "Təsdiqlə",
  },
  fil: {
    selectLanguageTitle: "Piliin ang iyong wika",
    selectLanguageDescription: "Tapikin ang wikang gusto mong basahin at gamitin sa screen na ito.",
    whatYouSay: "Ang sinasabi mo",
    whatYouSayHint: "Lalabas dito ang iyong sinasabi habang nakapindot ang button.",
    operatorTranslation: "Salin ng operator",
    operatorTranslationHint: "Lalabas dito ang isinaling sagot ng operator.",
    conversationHistory: "Kasaysayan ng usapan",
    conversationHistoryHint: "Lalabas dito ang mga nakumpirmang palitan ng kasalukuyang session.",
    sessionContext: "Konteksto ng session",
    sessionTurns: (count) => `${count} palitan`,
    holdToSpeak: "Pindutin nang matagal para magsalita",
    pressAndSpeak: "Pindutin at magsalita",
    waitingAvailability: "Naghihintay ng kahandaan",
    changeLanguage: "Palitan ang wika",
    closeSession: "Isara ang session",
    currentLanguage: "Wika",
    confirmCloseSession: "Isara ang kasalukuyang session",
    confirmCloseSessionDescription: "Mabubura ang kasalukuyang usapan sa parehong screen.",
    cancel: "Kanselahin",
    confirm: "Kumpirmahin",
  },
  kn: {
    selectLanguageTitle: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    selectLanguageDescription: "ಈ ಪರದೆಯಲ್ಲಿ ಓದಿ ಬಳಸಲು ಬಯಸುವ ಭಾಷೆಯನ್ನು ತಟ್ಟಿ ಆಯ್ಕೆಮಾಡಿ.",
    whatYouSay: "ನೀವು ಹೇಳುವುದು",
    whatYouSayHint: "ನೀವು ಬಟನ್ ಒತ್ತಿಹಿಡಿದಿರುವವರೆಗೆ ನಿಮ್ಮ ಮಾತು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.",
    operatorTranslation: "ಆಪರೇಟರ್ ಅನುವಾದ",
    operatorTranslationHint: "ಆಪರೇಟರ್‌ನ ಅನುವಾದಿತ ಉತ್ತರ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.",
    conversationHistory: "ಸಂಭಾಷಣೆ ಇತಿಹಾಸ",
    conversationHistoryHint: "ಪ್ರಸ್ತುತ ಸೆಷನ್‌ನ ದೃಢೀಕೃತ ತಿರುವುಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.",
    sessionContext: "ಸೆಷನ್ ಸಂದರ್ಭ",
    sessionTurns: (count) => `${count} ತಿರುವುಗಳು`,
    holdToSpeak: "ಮಾತನಾಡಲು ಒತ್ತಿಹಿಡಿಯಿರಿ",
    pressAndSpeak: "ಒತ್ತಿ ಮಾತನಾಡಿ",
    waitingAvailability: "ಲಭ್ಯತೆಗೆ ಕಾಯುತ್ತಿದೆ",
    changeLanguage: "ಭಾಷೆ ಬದಲಿಸಿ",
    closeSession: "ಸೆಷನ್ ಮುಚ್ಚಿ",
    currentLanguage: "ಭಾಷೆ",
    confirmCloseSession: "ಪ್ರಸ್ತುತ ಸೆಷನ್ ಮುಚ್ಚಿ",
    confirmCloseSessionDescription: "ಪ್ರಸ್ತುತ ಸಂಭಾಷಣೆ ಎರಡೂ ಪರದೆಗಳಲ್ಲಿ ಅಳಿಸಲಾಗುತ್ತದೆ.",
    cancel: "ರದ್ದುಮಾಡಿ",
    confirm: "ದೃಢೀಕರಿಸಿ",
  },
  kk: {
    selectLanguageTitle: "Тіліңізді таңдаңыз",
    selectLanguageDescription: "Осы экранда оқып, пайдаланғыңыз келетін тілді түртіңіз.",
    whatYouSay: "Не айтасыз",
    whatYouSayHint: "Түймені басып тұрған кезде сөзіңіз осында көрсетіледі.",
    operatorTranslation: "Оператор аудармасы",
    operatorTranslationHint: "Оператордың аударылған жауабы осында көрсетіледі.",
    conversationHistory: "Сөйлесу тарихы",
    conversationHistoryHint: "Ағымдағы сессияның расталған алмасулары осында көрсетіледі.",
    sessionContext: "Сессия контексті",
    sessionTurns: (count) => `${count} алмасу`,
    holdToSpeak: "Сөйлеу үшін басып тұрыңыз",
    pressAndSpeak: "Басып сөйлеңіз",
    waitingAvailability: "Дайындықты күтуде",
    changeLanguage: "Тілді өзгерту",
    closeSession: "Сессияны жабу",
    currentLanguage: "Тіл",
    confirmCloseSession: "Ағымдағы сессияны жабу",
    confirmCloseSessionDescription: "Ағымдағы әңгіме екі экранда да тазаланады.",
    cancel: "Бас тарту",
    confirm: "Растау",
  },
  mr: {
    selectLanguageTitle: "तुमची भाषा निवडा",
    selectLanguageDescription: "या स्क्रीनवर वाचण्यासाठी आणि वापरण्यासाठी हवी असलेली भाषा स्पर्श करा.",
    whatYouSay: "तुम्ही काय म्हणता",
    whatYouSayHint: "तुम्ही बटण दाबून ठेवताना तुमचा आवाज येथे दिसेल.",
    operatorTranslation: "ऑपरेटरचे भाषांतर",
    operatorTranslationHint: "ऑपरेटरचे भाषांतरित उत्तर येथे दिसेल.",
    conversationHistory: "संभाषण इतिहास",
    conversationHistoryHint: "सध्याच्या सत्रातील पुष्टी केलेले टप्पे येथे दिसतील.",
    sessionContext: "सत्र संदर्भ",
    sessionTurns: (count) => `${count} फेऱ्या`,
    holdToSpeak: "बोलण्यासाठी दाबून ठेवा",
    pressAndSpeak: "दाबा आणि बोला",
    waitingAvailability: "उपलब्धतेची वाट पाहत आहे",
    changeLanguage: "भाषा बदला",
    closeSession: "सत्र बंद करा",
    currentLanguage: "भाषा",
    confirmCloseSession: "सध्याचे सत्र बंद करा",
    confirmCloseSessionDescription: "सध्याचे संभाषण दोन्ही स्क्रीनवर साफ केले जाईल.",
    cancel: "रद्द करा",
    confirm: "पुष्टी करा",
  },
  ne: {
    selectLanguageTitle: "आफ्नो भाषा छान्नुहोस्",
    selectLanguageDescription: "यो स्क्रिनमा पढ्न र प्रयोग गर्न चाहेको भाषा छुनुहोस्।",
    whatYouSay: "तपाईंले भन्नुभएको कुरा",
    whatYouSayHint: "तपाईंले बटन थिचिरहँदा तपाईंको आवाज यहाँ देखिन्छ।",
    operatorTranslation: "अपरेटरको अनुवाद",
    operatorTranslationHint: "अपरेटरको अनुवादित उत्तर यहाँ देखिन्छ।",
    conversationHistory: "कुराकानी इतिहास",
    conversationHistoryHint: "हालको सत्रका पुष्टि भएका पालाहरू यहाँ देखिन्छन्।",
    sessionContext: "सत्र सन्दर्भ",
    sessionTurns: (count) => `${count} पालो`,
    holdToSpeak: "बोल्न थिचेर राख्नुहोस्",
    pressAndSpeak: "थिच्नुहोस् र बोल्नुहोस्",
    waitingAvailability: "उपलब्धताको प्रतीक्षामा",
    changeLanguage: "भाषा परिवर्तन गर्नुहोस्",
    closeSession: "सत्र बन्द गर्नुहोस्",
    currentLanguage: "भाषा",
    confirmCloseSession: "हालको सत्र बन्द गर्नुहोस्",
    confirmCloseSessionDescription: "हालको कुराकानी दुवै स्क्रिनबाट खाली गरिनेछ।",
    cancel: "रद्द गर्नुहोस्",
    confirm: "पुष्टि गर्नुहोस्",
  },
  eu: {
    selectLanguageTitle: "Hautatu zure hizkuntza",
    selectLanguageDescription: "Ukitu pantaila honetan irakurri eta erabili nahi duzun hizkuntza.",
    whatYouSay: "Esaten duzuna",
    whatYouSayHint: "Zure ahotsa hemen agertuko da botoia sakatuta duzun bitartean.",
    operatorTranslation: "Operadorearen itzulpena",
    operatorTranslationHint: "Operadorearen erantzun itzulia hemen agertuko da.",
    conversationHistory: "Elkarrizketa historia",
    conversationHistoryHint: "Uneko saioaren baieztatutako txandak hemen agertuko dira.",
    sessionContext: "Saioaren testuingurua",
    sessionTurns: (count) => `${count} txanda`,
    holdToSpeak: "Eduki sakatuta hitz egiteko",
    pressAndSpeak: "Sakatu eta hitz egin",
    waitingAvailability: "Prest egotearen zain",
    changeLanguage: "Aldatu hizkuntza",
    closeSession: "Itxi saioa",
    currentLanguage: "Hizkuntza",
    confirmCloseSession: "Itxi uneko saioa",
    confirmCloseSessionDescription: "Uneko elkarrizketa bi pantailatan ezabatuko da.",
    cancel: "Utzi",
    confirm: "Baieztatu",
  },
  gl: {
    selectLanguageTitle: "Escolle o teu idioma",
    selectLanguageDescription: "Toca o idioma que queres ler e usar nesta pantalla.",
    whatYouSay: "O que dis",
    whatYouSayHint: "A túa voz aparecerá aquí mentres mantés premido o botón.",
    operatorTranslation: "Tradución do operador",
    operatorTranslationHint: "A resposta traducida do operador aparecerá aquí.",
    conversationHistory: "Historial da conversa",
    conversationHistoryHint: "Aquí aparecerán as quendas confirmadas da sesión actual.",
    sessionContext: "Contexto da sesión",
    sessionTurns: (count) => `${count} quendas`,
    holdToSpeak: "Mantén premido para falar",
    pressAndSpeak: "Preme e fala",
    waitingAvailability: "Agardando dispoñibilidade",
    changeLanguage: "Cambiar idioma",
    closeSession: "Pechar sesión",
    currentLanguage: "Idioma",
    confirmCloseSession: "Pechar a sesión actual",
    confirmCloseSessionDescription: "A conversa actual borrarase nas dúas pantallas.",
    cancel: "Cancelar",
    confirm: "Confirmar",
  },
  ka: {
    selectLanguageTitle: "აირჩიეთ თქვენი ენა",
    selectLanguageDescription: "შეეხეთ ენას, რომლის წაკითხვაც და გამოყენებაც გსურთ ამ ეკრანზე.",
    whatYouSay: "რას ამბობთ",
    whatYouSayHint: "თქვენი საუბარი აქ გამოჩნდება, სანამ ღილაკს დაჭერილს გეჭირებათ.",
    operatorTranslation: "ოპერატორის თარგმანი",
    operatorTranslationHint: "ოპერატორის თარგმნილი პასუხი აქ გამოჩნდება.",
    conversationHistory: "საუბრის ისტორია",
    conversationHistoryHint: "მიმდინარე სესიის დადასტურებული რიგები აქ გამოჩნდება.",
    sessionContext: "სესიის კონტექსტი",
    sessionTurns: (count) => `${count} მონაცვლეობა`,
    holdToSpeak: "სალაპარაკოდ დააჭირეთ და გააჩერეთ",
    pressAndSpeak: "დააჭირეთ და ილაპარაკეთ",
    waitingAvailability: "მზადყოფნის მოლოდინში",
    changeLanguage: "ენის შეცვლა",
    closeSession: "სესიის დახურვა",
    currentLanguage: "ენა",
    confirmCloseSession: "მიმდინარე სესიის დახურვა",
    confirmCloseSessionDescription: "მიმდინარე საუბარი ორივე ეკრანზე გასუფთავდება.",
    cancel: "გაუქმება",
    confirm: "დადასტურება",
  },
  mk: {
    selectLanguageTitle: "Изберете го вашиот јазик",
    selectLanguageDescription: "Допрете го јазикот што сакате да го читате и користите на овој екран.",
    whatYouSay: "Што кажувате",
    whatYouSayHint: "Вашиот говор ќе се појави тука додека го држите копчето притиснато.",
    operatorTranslation: "Превод на операторот",
    operatorTranslationHint: "Преведениот одговор на операторот ќе се појави тука.",
    conversationHistory: "Историја на разговор",
    conversationHistoryHint: "Потврдените размени од тековната сесија ќе се појават тука.",
    sessionContext: "Контекст на сесијата",
    sessionTurns: (count) => `${count} размени`,
    holdToSpeak: "Држете за да зборувате",
    pressAndSpeak: "Притиснете и зборувајте",
    waitingAvailability: "Чека подготвеност",
    changeLanguage: "Смени јазик",
    closeSession: "Затвори ја сесијата",
    currentLanguage: "Јазик",
    confirmCloseSession: "Затвори ја тековната сесија",
    confirmCloseSessionDescription: "Тековниот разговор ќе се избрише на двата екрана.",
    cancel: "Откажи",
    confirm: "Потврди",
  },
  mn: {
    selectLanguageTitle: "Хэлээ сонгоно уу",
    selectLanguageDescription: "Энэ дэлгэц дээр уншиж ашиглахыг хүссэн хэлээ товшино уу.",
    whatYouSay: "Таны хэлэх зүйл",
    whatYouSayHint: "Та товчийг дарж байх үед таны яриа энд харагдана.",
    operatorTranslation: "Операторын орчуулга",
    operatorTranslationHint: "Операторын орчуулсан хариу энд харагдана.",
    conversationHistory: "Ярианы түүх",
    conversationHistoryHint: "Одоогийн сессийн баталгаажсан ээлжүүд энд харагдана.",
    sessionContext: "Сессийн нөхцөл",
    sessionTurns: (count) => `${count} ээлж`,
    holdToSpeak: "Ярихын тулд дарж барина уу",
    pressAndSpeak: "Дарж ярь",
    waitingAvailability: "Бэлэн байдлыг хүлээж байна",
    changeLanguage: "Хэл өөрчлөх",
    closeSession: "Сесс хаах",
    currentLanguage: "Хэл",
    confirmCloseSession: "Одоогийн сессийг хаах",
    confirmCloseSessionDescription: "Одоогийн яриа хоёр дэлгэц дээр хоёуланд нь цэвэрлэгдэнэ.",
    cancel: "Цуцлах",
    confirm: "Батлах",
  },
  si: {
    selectLanguageTitle: "ඔබේ භාෂාව තෝරන්න",
    selectLanguageDescription: "මෙම තිරයේ කියවීමට සහ භාවිතා කිරීමට අවශ්‍ය භාෂාව තට්ටු කරන්න.",
    whatYouSay: "ඔබ කියන දේ",
    whatYouSayHint: "ඔබ බොත්තම තබාගෙන සිටින විට ඔබේ කථාව මෙහි දිස්වෙයි.",
    operatorTranslation: "ඔපරේටර්ගේ පරිවර්තනය",
    operatorTranslationHint: "ඔපරේටර්ගේ පරිවර්තනය කළ පිළිතුර මෙහි දිස්වෙයි.",
    conversationHistory: "සංවාද ඉතිහාසය",
    conversationHistoryHint: "වත්මන් සැසියේ තහවුරු කළ වාර මෙහි දිස්වෙයි.",
    sessionContext: "සැසි සන්දර්භය",
    sessionTurns: (count) => `${count} වාර`,
    holdToSpeak: "කතා කිරීමට ඔබා තබන්න",
    pressAndSpeak: "ඔබා කතා කරන්න",
    waitingAvailability: "සූදානම සඳහා බලා සිටී",
    changeLanguage: "භාෂාව වෙනස් කරන්න",
    closeSession: "සැසිය වසන්න",
    currentLanguage: "භාෂාව",
    confirmCloseSession: "වත්මන් සැසිය වසන්න",
    confirmCloseSessionDescription: "වත්මන් සංවාදය තිර දෙකෙන්ම මකා දමනු ඇත.",
    cancel: "අවලංගු කරන්න",
    confirm: "තහවුරු කරන්න",
  },
  so: {
    selectLanguageTitle: "Dooro luqaddaada",
    selectLanguageDescription: "Taabo luqadda aad rabto inaad ku akhrido oo ku isticmaasho shaashaddan.",
    whatYouSay: "Waxaad sheegto",
    whatYouSayHint: "Codkaaga halkan ayuu ka muuqan doonaa inta aad batoonka hayso.",
    operatorTranslation: "Tarjumaadda hawlwadeenka",
    operatorTranslationHint: "Jawaabta hawlwadeenka ee la turjumay halkan ayay ka muuqan doontaa.",
    conversationHistory: "Taariikhda wada hadalka",
    conversationHistoryHint: "Wareegyada la xaqiijiyay ee kulanka hadda socda halkan ayay ka muuqan doonaan.",
    sessionContext: "Macnaha kulanka",
    sessionTurns: (count) => `${count} wareeg`,
    holdToSpeak: "Qabo si aad u hadasho",
    pressAndSpeak: "Riix oo hadal",
    waitingAvailability: "Sugaya diyaar ahaansho",
    changeLanguage: "Beddel luqadda",
    closeSession: "Xir kulanka",
    currentLanguage: "Luqad",
    confirmCloseSession: "Xir kulanka hadda socda",
    confirmCloseSessionDescription: "Wadahadalka hadda socda waxaa laga tirtiri doonaa labada shaashadood.",
    cancel: "Jooji",
    confirm: "Xaqiiji",
  },
  uz: {
    selectLanguageTitle: "Tilni tanlang",
    selectLanguageDescription: "Ushbu ekranda o‘qish va ishlatmoqchi bo‘lgan tilni bosing.",
    whatYouSay: "Siz aytgan narsa",
    whatYouSayHint: "Tugmani bosib turganingizda nutqingiz shu yerda ko‘rinadi.",
    operatorTranslation: "Operator tarjimasi",
    operatorTranslationHint: "Operatorning tarjima qilingan javobi shu yerda ko‘rinadi.",
    conversationHistory: "Suhbat tarixi",
    conversationHistoryHint: "Joriy sessiyaning tasdiqlangan almashuvlari shu yerda ko‘rinadi.",
    sessionContext: "Sessiya konteksti",
    sessionTurns: (count) => `${count} almashuv`,
    holdToSpeak: "Gapirish uchun bosib turing",
    pressAndSpeak: "Bosing va gapiring",
    waitingAvailability: "Tayyor holat kutilmoqda",
    changeLanguage: "Tilni o‘zgartirish",
    closeSession: "Sessiyani yopish",
    currentLanguage: "Til",
    confirmCloseSession: "Joriy sessiyani yopish",
    confirmCloseSessionDescription: "Joriy suhbat ikkala ekranda ham tozalanadi.",
    cancel: "Bekor qilish",
    confirm: "Tasdiqlash",
  },
  yue: {
    selectLanguageTitle: "選擇你的語言",
    selectLanguageDescription: "點選你想喺呢個畫面閱讀同使用嘅語言。",
    whatYouSay: "你講嘅內容",
    whatYouSayHint: "當你按住按鈕時，你嘅說話會顯示喺呢度。",
    operatorTranslation: "操作員翻譯",
    operatorTranslationHint: "操作員翻譯後嘅回覆會顯示喺呢度。",
    conversationHistory: "對話記錄",
    conversationHistoryHint: "目前會話已確認嘅輪次會顯示喺呢度。",
    sessionContext: "會話內容",
    sessionTurns: (count) => `${count} 輪`,
    holdToSpeak: "按住講嘢",
    pressAndSpeak: "按下並講話",
    waitingAvailability: "等待可用",
    changeLanguage: "更改語言",
    closeSession: "關閉會話",
    currentLanguage: "語言",
    confirmCloseSession: "關閉目前會話",
    confirmCloseSessionDescription: "目前對話會喺兩個畫面上清除。",
    cancel: "取消",
    confirm: "確認",
  },
  "zh-Hant": {
    selectLanguageTitle: "選擇您的語言",
    selectLanguageDescription: "點選您想在這個畫面閱讀並使用的語言。",
    whatYouSay: "您說的內容",
    whatYouSayHint: "當您按住按鈕時，您的語音會顯示在這裡。",
    operatorTranslation: "操作員翻譯",
    operatorTranslationHint: "操作員翻譯後的回覆會顯示在這裡。",
    conversationHistory: "對話紀錄",
    conversationHistoryHint: "目前工作階段已確認的輪次會顯示在這裡。",
    sessionContext: "工作階段內容",
    sessionTurns: (count) => `${count} 輪`,
    holdToSpeak: "按住即可說話",
    pressAndSpeak: "按下並說話",
    waitingAvailability: "等待可用",
    changeLanguage: "變更語言",
    closeSession: "關閉工作階段",
    currentLanguage: "語言",
    confirmCloseSession: "關閉目前工作階段",
    confirmCloseSessionDescription: "目前對話會在兩個畫面上清除。",
    cancel: "取消",
    confirm: "確認",
  }
};

export const EXTENDED_VISITOR_STATUS_LABELS: Record<string, Record<OperatorStatus, string>> = {
  be: {
    booting: "Запуск",
    "language-selection": "Выбар мовы",
    ready: "Гатова",
    listening: "Слухае",
    translating: "Перакладае",
    error: "Памылка"
  },
  bg: {
    booting: "Стартиране",
    "language-selection": "Избор на език",
    ready: "Готово",
    listening: "Слуша",
    translating: "Превежда",
    error: "Грешка"
  },
  bs: {
    booting: "Pokretanje",
    "language-selection": "Izbor jezika",
    ready: "Spremno",
    listening: "Sluša",
    translating: "Prevodi",
    error: "Greška"
  },
  ca: {
    booting: "Iniciant",
    "language-selection": "Selecció d'idioma",
    ready: "A punt",
    listening: "Escoltant",
    translating: "Traduïnt",
    error: "Error"
  },
  cs: {
    booting: "Spouštění",
    "language-selection": "Výběr jazyka",
    ready: "Připraveno",
    listening: "Naslouchá",
    translating: "Překládá",
    error: "Chyba"
  },
  cy: {
    booting: "Yn cychwyn",
    "language-selection": "Dewis iaith",
    ready: "Barod",
    listening: "Yn gwrando",
    translating: "Yn cyfieithu",
    error: "Gwall"
  },
  da: {
    booting: "Starter",
    "language-selection": "Sprogvalg",
    ready: "Klar",
    listening: "Lytter",
    translating: "Oversætter",
    error: "Fejl"
  },
  et: {
    booting: "Käivitub",
    "language-selection": "Keele valik",
    ready: "Valmis",
    listening: "Kuulab",
    translating: "Tõlgib",
    error: "Viga"
  },
  fi: {
    booting: "Käynnistyy",
    "language-selection": "Kielen valinta",
    ready: "Valmis",
    listening: "Kuuntelee",
    translating: "Kääntää",
    error: "Virhe"
  },
  ga: {
    booting: "Ag tosú",
    "language-selection": "Roghnú teanga",
    ready: "Réidh",
    listening: "Ag éisteacht",
    translating: "Ag aistriú",
    error: "Earráid"
  },
  hr: {
    booting: "Pokretanje",
    "language-selection": "Odabir jezika",
    ready: "Spremno",
    listening: "Sluša",
    translating: "Prevodi",
    error: "Greška"
  },
  is: {
    booting: "Ræsir",
    "language-selection": "Val á tungumáli",
    ready: "Tilbúið",
    listening: "Hlustar",
    translating: "Þýðir",
    error: "Villa"
  },
  lt: {
    booting: "Paleidžiama",
    "language-selection": "Kalbos pasirinkimas",
    ready: "Paruošta",
    listening: "Klausosi",
    translating: "Verčia",
    error: "Klaida"
  },
  lv: {
    booting: "Palaiž",
    "language-selection": "Valodas izvēle",
    ready: "Gatavs",
    listening: "Klausās",
    translating: "Tulko",
    error: "Kļūda"
  },
  mt: {
    booting: "Qed jibda",
    "language-selection": "Għażla tal-lingwa",
    ready: "Lest",
    listening: "Qed jisma'",
    translating: "Qed jittraduċi",
    error: "Żball"
  },
  mi: {
    booting: "E tīmata ana",
    "language-selection": "Kōwhiri reo",
    ready: "Kua rite",
    listening: "E whakarongo ana",
    translating: "E whakamāori ana",
    error: "Hapa"
  },
  nb: {
    booting: "Starter",
    "language-selection": "Språkvalg",
    ready: "Klar",
    listening: "Lytter",
    translating: "Oversetter",
    error: "Feil"
  },
  sk: {
    booting: "Spúšťa sa",
    "language-selection": "Výber jazyka",
    ready: "Pripravené",
    listening: "Počúva",
    translating: "Prekladá",
    error: "Chyba"
  },
  sq: {
    booting: "Po niset",
    "language-selection": "Zgjedhja e gjuhës",
    ready: "Gati",
    listening: "Po dëgjon",
    translating: "Po përkthen",
    error: "Gabim"
  },
  "sr-Cyrl": {
    booting: "Покретање",
    "language-selection": "Избор језика",
    ready: "Спремно",
    listening: "Слуша",
    translating: "Преводи",
    error: "Грешка"
  },
  "sr-Latn": {
    booting: "Pokretanje",
    "language-selection": "Izbor jezika",
    ready: "Spremno",
    listening: "Sluša",
    translating: "Prevodi",
    error: "Greška"
  },
  sl: {
    booting: "Zagon",
    "language-selection": "Izbira jezika",
    ready: "Pripravljeno",
    listening: "Posluša",
    translating: "Prevaja",
    error: "Napaka"
  },
  sv: {
    booting: "Startar",
    "language-selection": "Språkval",
    ready: "Klar",
    listening: "Lyssnar",
    translating: "Översätter",
    error: "Fel"
  },
  hu: {
    booting: "Indul",
    "language-selection": "Nyelvválasztás",
    ready: "Kész",
    listening: "Hallgat",
    translating: "Fordít",
    error: "Hiba"
  },
  hy: {
    booting: "Մեկնարկում է",
    "language-selection": "Լեզվի ընտրություն",
    ready: "Պատրաստ է",
    listening: "Լսում է",
    translating: "Թարգմանում է",
    error: "Սխալ"
  },
  az: {
    booting: "Başlayır",
    "language-selection": "Dil seçimi",
    ready: "Hazırdır",
    listening: "Dinləyir",
    translating: "Tərcümə edir",
    error: "Xəta"
  },
  fil: {
    booting: "Nagsisimula",
    "language-selection": "Pagpili ng wika",
    ready: "Handa na",
    listening: "Nakikinig",
    translating: "Nagsasalin",
    error: "Error"
  },
  kn: {
    booting: "ಪ್ರಾರಂಭವಾಗುತ್ತಿದೆ",
    "language-selection": "ಭಾಷೆ ಆಯ್ಕೆ",
    ready: "ಸಿದ್ಧ",
    listening: "ಕೇಳುತ್ತಿದೆ",
    translating: "ಅನುವಾದಿಸುತ್ತಿದೆ",
    error: "ದೋಷ"
  },
  kk: {
    booting: "Іске қосылуда",
    "language-selection": "Тілді таңдау",
    ready: "Дайын",
    listening: "Тыңдап тұр",
    translating: "Аударып тұр",
    error: "Қате"
  },
  mr: {
    booting: "सुरू होत आहे",
    "language-selection": "भाषा निवड",
    ready: "तयार",
    listening: "ऐकत आहे",
    translating: "भाषांतर करत आहे",
    error: "त्रुटी"
  },
  ne: {
    booting: "सुरु हुँदैछ",
    "language-selection": "भाषा चयन",
    ready: "तयार",
    listening: "सुनिरहेको छ",
    translating: "अनुवाद गर्दैछ",
    error: "त्रुटि"
  },
  eu: {
    booting: "Abiatzen",
    "language-selection": "Hizkuntza hautapena",
    ready: "Prest",
    listening: "Entzuten",
    translating: "Itzultzen",
    error: "Errorea"
  },
  gl: {
    booting: "Iniciando",
    "language-selection": "Selección de idioma",
    ready: "Listo",
    listening: "Escoitando",
    translating: "Traducindo",
    error: "Erro"
  },
  ka: {
    booting: "იწყება",
    "language-selection": "ენის არჩევა",
    ready: "მზადაა",
    listening: "უსმენს",
    translating: "თარგმნის",
    error: "შეცდომა"
  },
  mk: {
    booting: "Се стартува",
    "language-selection": "Избор на јазик",
    ready: "Подготвено",
    listening: "Слуша",
    translating: "Преведува",
    error: "Грешка"
  },
  mn: {
    booting: "Эхэлж байна",
    "language-selection": "Хэл сонголт",
    ready: "Бэлэн",
    listening: "Сонсож байна",
    translating: "Орчуулж байна",
    error: "Алдаа"
  },
  si: {
    booting: "ආරම්භ වෙමින්",
    "language-selection": "භාෂා තේරීම",
    ready: "සූදානම්",
    listening: "සවන් දෙයි",
    translating: "පරිවර්තනය කරයි",
    error: "දෝෂය"
  },
  so: {
    booting: "Bilaabmaya",
    "language-selection": "Doorashada luqadda",
    ready: "Diyaar",
    listening: "Dhageysanaya",
    translating: "Tarjumaya",
    error: "Khalad"
  },
  uz: {
    booting: "Ishga tushmoqda",
    "language-selection": "Til tanlash",
    ready: "Tayyor",
    listening: "Tinglamoqda",
    translating: "Tarjima qilmoqda",
    error: "Xato"
  },
  yue: {
    booting: "啟動中",
    "language-selection": "選擇語言",
    ready: "就緒",
    listening: "聆聽中",
    translating: "翻譯中",
    error: "錯誤"
  },
  "zh-Hant": {
    booting: "啟動中",
    "language-selection": "語言選擇",
    ready: "就緒",
    listening: "聆聽中",
    translating: "翻譯中",
    error: "錯誤"
  }
};
