export function getSetupWizardControlCoreLocalizationCopyScript(initialWizardUiLanguage: string): string {
  return `      let wizardUiLanguage = ${initialWizardUiLanguage};
      const copyByLanguage = {
        it: {
            envRequiredMonitors: "Monitor richiesti",
            envPttRelease: "Ritardo rilascio PTT ms",
            envProviderTimeout: "Timeout provider ms",
            envChatGptSilence: "Soglia silenzio ChatGPT",
            appModeKiosk: "Kiosk live",
            appModeDemo: "Demo scripted loop",
            microphoneProfileDedicated: "Due microfoni dedicati",
            microphoneProfileShared: "Un microfono condiviso",
            disclosureStandard: "Standard localizzato",
            disclosureCustom: "Testo personalizzato globale",
            disclosureDisabled: "Disattiva avviso",
            booleanDisabled: "Disattivato",
            booleanEnabled: "Attivato",
            disclosureDisabledLabel: "Avviso disattivato",
            sectionNeedsAttention: "Sezione da completare",
            sectionComplete: "Sezione completa",
            checklistReadyTitle: "Configurazione essenziale completa",
            checklistReadyBody: "Monitor, microfoni e provider risultano assegnati. Puoi eseguire i test e salvare.",
            displayPending: "Monitor da assegnare",
            displayUnassignedSide: "monitor {side} non assegnato",
            microphonePending: "Microfono da assegnare",
            microphoneAssignedToSide: "Assegnato al lato {side}",
            microphoneUnassignedSide: "microfono {side} non assegnato",
            reviewChecklist: "Checklist",
            reviewReadyToSave: "Pronta per il salvataggio",
            reviewOpenItems: "{count} punti aperti",
            reviewDisplays: "Monitor",
            reviewDisplayReady: "Assegnazioni complete",
            reviewDisplayMissing: "Assegnazioni incomplete",
            reviewMicrophones: "Microfoni",
            reviewMicrophoneReady: "Configurazione coerente",
            reviewMicrophoneMissing: "Verifica assegnazioni",
            reviewProvider: "Provider",
            reviewAiNotice: "Avviso AI",
            reviewAutostart: "Avvio automatico",
            reviewInitialLanguages: "Flusso lingue runtime",
            reviewInitialLanguagesFix: "Verifica i default runtime salvati",
            reviewInitialLanguagesReady: "Scelta lingue demandata alle postazioni",
            reviewAzureTts: "Azure TTS",
            reviewAzureTtsFix: "Catalogo o voci A/B da completare",
            reviewAzureTtsReady: "Copertura A/B pronta",
            reviewAutostartEnabled: "Attivo",
            reviewAutostartDisabled: "Disattivato",
    reviewAutostartPendingEnable: "Attivazione avvio automatico in corso",
    reviewAutostartPendingDisable: "Disattivazione avvio automatico in corso",
            autostartUnavailable: "Disponibile solo nelle installazioni packaged di Windows.",
            autostartEnabledNote: "OnlySpeech si avviera' automaticamente all'accesso dell'utente corrente.",
            autostartDisabledNote: "OnlySpeech non si avviera' automaticamente all'accesso.",
    autostartWillEnableOnSave: "L'avvio automatico e' in fase di attivazione.",
    autostartWillDisableOnSave: "L'avvio automatico e' in fase di disattivazione.",
            bothDisplaysAssigned: "Entrambi i monitor risultano assegnati.",
            displayUnassignedBadge: "Monitor non assegnato",
            assignStationA: "Assegna a Postazione A",
            assignStationB: "Assegna a Postazione B",
            stationASelected: "Postazione A selezionata",
            stationBSelected: "Postazione B selezionata",
            removeAssignment: "Rimuovi assegnazione",
            displayAssignedStatus: "Display {id} assegnato al lato {side}.",
            displayAssignmentRemoved: "Assegnazione monitor rimossa.",
            displayAssignmentUpdateFailed: "Impossibile aggiornare l'assegnazione del monitor",
            microphonePermissionDenied: "Permesso microfono non concesso: {detail}",
            grantMicrophonePermission: "Concedi il permesso microfono.",
            twoDistinctMicrophonesRequired: "Servono due microfoni selezionabili distinti per completare il provisioning.",
            selectOneSharedMicrophone: "Seleziona almeno un microfono per il profilo condiviso.",
            demoNeedsNoMicrophones: "La modalita demo non richiede microfoni live per il loop runtime.",
            savedMicrophoneUnavailableReplace: "Il microfono salvato per il lato {side} non e' piu disponibile. Salva per aggiornarlo con {label}.",
            savedMicrophoneUnavailableSelect: "Il microfono salvato per il lato {side} non e' piu disponibile. Seleziona un nuovo microfono e salva.",
            uncategorizedMicrophoneGroup: "Altro",
            noMicrophonesDetected: "Nessun microfono rilevato. Usa \\"Rileva microfoni\\" per aggiornare l'inventario.",
            selectMicrophone: "Seleziona microfono",
            monitorUnassigned: "nessun monitor assegnato",
            assignedMicrophoneLabel: "Microfono assegnato",
            sharedProfileHint: "Profilo condiviso: puoi assegnare lo stesso microfono a entrambe le postazioni.",
            clearMicrophoneAssignmentAria: "Rimuovi assegnazione microfono lato {side}",
            clearMicrophoneAssignment: "Rimuovi assegnazione",
            microphoneUpdated: "Microfono lato {side} aggiornato.",
            microphoneRemoved: "Microfono lato {side} rimosso.",
            microphoneUpdateFailed: "Impossibile aggiornare il microfono",
            microphoneRemoveFailed: "Impossibile rimuovere il microfono",
            microphoneTestStopping: "Arresto...",
            microphoneTestStop: "Ferma test",
            microphoneTestStart: "Avvia test",
            stationsProbeLabel: "Rilevamento microfoni in corso",
            stationsProbeDetail: "Attendi il completamento del probe prima di assegnare i nuovi dispositivi.",
            providerTestLabel: "Test provider in corso",
            providerTestDetail: "Il provider sta elaborando la traduzione di prova.",
            providerSpeechAzureLabel: "Test live Azure in corso",
            providerSpeechChatGptLabel: "Invio final-turn al provider",
            providerSpeechOllamaLabel: "Test vocale non disponibile",
            providerSpeechAzureDetail: "Azure Speech resta in ascolto sul microfono selezionato.",
            providerSpeechChatGptDetail: "ChatGPT sta elaborando l'audio del turn finale.",
            providerSpeechOllamaDetail: "Ollama resta disponibile solo per traduzione testuale e diagnostica modello.",
            providerCapabilityNote:
              "Disponibilita STT / traduzione / TTS verificata sulle lingue selezionate nel registry del provider.",
            probeMicrophonesIdle: "Rileva microfoni",
            probeMicrophonesBusy: "Rilevamento...",
            probeMicrophonesDisabledReason: "Attendi la fine del rilevamento microfoni prima di avviare un nuovo probe.",
            saveSectionIdle: "Salva",
            saveSectionBusy: "Salvataggio...",
            saveAndCloseIdle: "Applica e chiudi wizard",
            saveAndCloseBusy: "Applicazione e chiusura...",
            saveDisabledBusy: "Attendi la fine del salvataggio in corso prima di avviare un nuovo salvataggio.",
            providerTestIdle: "Esegui test provider",
            providerTestBusy: "Test provider in corso...",
            azureLiveBusy: "Test Azure live in corso...",
            azureLiveStart: "Avvia test live Azure",
            providerSpeechDisabledBusy: "Attendi la fine del test provider vocale in corso.",
            providerSpeechDisabledProviderTest: "Attendi la fine del test provider testuale prima di avviare il test vocale.",
            providerSpeechDisabledInFlight: "Azure live sta ancora ascoltando dal microfono selezionato.",
            providerSpeechDisabledUnsupported: "Ollama non supporta test vocali live in OnlySpeech.",
            finalTurnStopAndSend: "Ferma e invia turn finale",
            finalTurnStart: "Avvia test final-turn",
            finalTurnSending: "Invio turn finale...",
            unnamedMicrophone: "Microfono senza nome",
            displayIdLabel: "Display ID",
            issueMissingDisplayA: "monitor A non assegnato",
            issueMissingDisplayB: "monitor B non assegnato",
            issueMissingMicrophoneA: "microfono A non assegnato",
            issueMissingMicrophoneB: "microfono B non assegnato",
            issueMissingSharedMicrophone: "microfono condiviso non assegnato",
            issueDistinctMicrophonesRequired: "servono due microfoni distinti",
            issueUnsupportedProvider: "provider non configurato",
            issueMissingProviderCredentials: "credenziali provider mancanti",
            issueAzureTextToSpeechCatalogUnavailable: "catalogo Azure TTS non disponibile",
            issueUnresolvedTargetTextToSpeech: "nessuna voce Azure compatibile per la lingua iniziale {side}",
            issueMissingWizardPassword: "password del wizard non configurata",
            issueWizardPasswordTooShort: "password troppo corta (minimo 12 caratteri)",
            issueWizardPasswordMismatch: "le password non coincidono"
          },
        en: {
            envRequiredMonitors: "Required displays",
            envPttRelease: "PTT release delay ms",
            envProviderTimeout: "Provider timeout ms",
            envChatGptSilence: "ChatGPT silence threshold",
            appModeKiosk: "Live kiosk",
            appModeDemo: "Demo scripted loop",
            microphoneProfileDedicated: "Two dedicated microphones",
            microphoneProfileShared: "One shared microphone",
            disclosureStandard: "Localized standard",
            disclosureCustom: "Global custom text",
            disclosureDisabled: "Disable notice",
            booleanDisabled: "Disabled",
            booleanEnabled: "Enabled",
            disclosureDisabledLabel: "Notice disabled",
            sectionNeedsAttention: "Section needs attention",
            sectionComplete: "Section complete",
            checklistReadyTitle: "Essential configuration complete",
            checklistReadyBody: "Displays, microphones, and provider are assigned. You can run tests and save.",
            displayPending: "Display to assign",
            displayUnassignedSide: "display {side} is not assigned",
            microphonePending: "Microphone to assign",
            microphoneAssignedToSide: "Assigned to side {side}",
            microphoneUnassignedSide: "microphone {side} is not assigned",
            reviewChecklist: "Checklist",
            reviewReadyToSave: "Ready to save",
            reviewOpenItems: "{count} open items",
            reviewDisplays: "Displays",
            reviewDisplayReady: "Assignments complete",
            reviewDisplayMissing: "Assignments incomplete",
            reviewMicrophones: "Microphones",
            reviewMicrophoneReady: "Configuration aligned",
            reviewMicrophoneMissing: "Review assignments",
            reviewProvider: "Provider",
            reviewAiNotice: "AI notice",
            reviewAutostart: "Automatic startup",
            reviewInitialLanguages: "Runtime language flow",
            reviewInitialLanguagesFix: "Review the saved runtime defaults",
            reviewInitialLanguagesReady: "Language choice happens on the stations",
            reviewAzureTts: "Azure TTS",
            reviewAzureTtsFix: "Catalog or A/B voices still missing",
            reviewAzureTtsReady: "A/B coverage ready",
            reviewAutostartEnabled: "Enabled",
            reviewAutostartDisabled: "Disabled",
    reviewAutostartPendingEnable: "Automatic startup is being enabled",
    reviewAutostartPendingDisable: "Automatic startup is being disabled",
            autostartUnavailable: "Available only in packaged Windows installs.",
            autostartEnabledNote: "OnlySpeech starts automatically when the current Windows user signs in.",
            autostartDisabledNote: "OnlySpeech does not start automatically at sign-in.",
    autostartWillEnableOnSave: "Automatic startup is being enabled.",
    autostartWillDisableOnSave: "Automatic startup is being disabled.",
            bothDisplaysAssigned: "Both displays are assigned.",
            displayUnassignedBadge: "Unassigned display",
            assignStationA: "Assign to Station A",
            assignStationB: "Assign to Station B",
            stationASelected: "Station A selected",
            stationBSelected: "Station B selected",
            removeAssignment: "Remove assignment",
            displayAssignedStatus: "Display {id} assigned to side {side}.",
            displayAssignmentRemoved: "Display assignment removed.",
            displayAssignmentUpdateFailed: "Unable to update the display assignment",
            microphonePermissionDenied: "Microphone permission denied: {detail}",
            grantMicrophonePermission: "Grant microphone permission.",
            twoDistinctMicrophonesRequired: "Two distinct selectable microphones are required to finish provisioning.",
            selectOneSharedMicrophone: "Select at least one microphone for the shared profile.",
            demoNeedsNoMicrophones: "Demo mode does not require live microphones for the runtime loop.",
            savedMicrophoneUnavailableReplace: "The saved microphone for side {side} is no longer available. Save to replace it with {label}.",
            savedMicrophoneUnavailableSelect: "The saved microphone for side {side} is no longer available. Select a new microphone and save.",
            uncategorizedMicrophoneGroup: "Other",
            noMicrophonesDetected: "No microphone detected. Use \\"Probe microphones\\" to refresh the inventory.",
            selectMicrophone: "Select microphone",
            monitorUnassigned: "no display assigned",
            assignedMicrophoneLabel: "Assigned microphone",
            sharedProfileHint: "Shared profile: you can assign the same microphone to both stations.",
            clearMicrophoneAssignmentAria: "Remove microphone assignment for side {side}",
            clearMicrophoneAssignment: "Remove assignment",
            microphoneUpdated: "Microphone for side {side} updated.",
            microphoneRemoved: "Microphone for side {side} removed.",
            microphoneUpdateFailed: "Unable to update the microphone",
            microphoneRemoveFailed: "Unable to remove the microphone",
            microphoneTestStopping: "Stopping...",
            microphoneTestStop: "Stop test",
            microphoneTestStart: "Start test",
            stationsProbeLabel: "Microphone probe in progress",
            stationsProbeDetail: "Wait for the probe to finish before assigning new devices.",
            providerTestLabel: "Provider test in progress",
            providerTestDetail: "The provider is processing the sample translation.",
            providerSpeechAzureLabel: "Azure live test in progress",
            providerSpeechChatGptLabel: "Uploading final-turn audio",
            providerSpeechOllamaLabel: "Speech test unavailable",
            providerSpeechAzureDetail: "Azure Speech is listening on the selected microphone.",
            providerSpeechChatGptDetail: "ChatGPT is processing the final-turn audio.",
            providerSpeechOllamaDetail: "Ollama remains available for text translation and model diagnostics only.",
            providerCapabilityNote:
              "STT / translation / TTS availability is checked against the selected provider language registry.",
            probeMicrophonesIdle: "Probe microphones",
            probeMicrophonesBusy: "Probing...",
            probeMicrophonesDisabledReason: "Wait for the current microphone probe to finish before starting a new probe.",
            saveSectionIdle: "Save",
            saveSectionBusy: "Saving...",
            saveAndCloseIdle: "Apply and close setup",
            saveAndCloseBusy: "Applying and closing...",
            saveDisabledBusy: "Wait for the active save operation to finish before starting another save.",
            providerTestIdle: "Run provider test",
            providerTestBusy: "Provider test in progress...",
            azureLiveBusy: "Azure live test in progress...",
            azureLiveStart: "Start Azure live test",
            providerSpeechDisabledBusy: "Wait for the active provider speech test to finish.",
            providerSpeechDisabledProviderTest: "Wait for the text provider test to finish before starting the microphone test.",
            providerSpeechDisabledInFlight: "Azure live validation is still listening on the selected microphone.",
            providerSpeechDisabledUnsupported: "Ollama does not support live speech tests in OnlySpeech.",
            finalTurnStopAndSend: "Stop and upload final turn",
            finalTurnStart: "Start final-turn test",
            finalTurnSending: "Uploading final turn...",
            unnamedMicrophone: "Unnamed microphone",
            displayIdLabel: "Display ID",
            issueMissingDisplayA: "display A is not assigned",
            issueMissingDisplayB: "display B is not assigned",
            issueMissingMicrophoneA: "microphone A is not assigned",
            issueMissingMicrophoneB: "microphone B is not assigned",
            issueMissingSharedMicrophone: "shared microphone is not assigned",
            issueDistinctMicrophonesRequired: "two distinct microphones are required",
            issueUnsupportedProvider: "provider is not configured",
            issueMissingProviderCredentials: "provider credentials are missing",
            issueAzureTextToSpeechCatalogUnavailable: "Azure TTS catalog is unavailable",
            issueUnresolvedTargetTextToSpeech: "no compatible Azure voice for initial language {side}",
            issueMissingWizardPassword: "wizard password not set",
            issueWizardPasswordTooShort: "password too short (minimum 12 characters)",
            issueWizardPasswordMismatch: "passwords do not match"
          }
      };
      copyByLanguage.es = {
        ...copyByLanguage.en,
        checklistReadyTitle: "Configuracion esencial completada",
        checklistReadyBody: "Monitores, microfonos y proveedor estan asignados. Puedes ejecutar las pruebas y guardar.",
        displayPending: "Monitor por asignar",
        displayUnassignedSide: "el monitor {side} no esta asignado",
        microphonePending: "Microfono por asignar",
        microphoneAssignedToSide: "Asignado al lado {side}",
        microphoneUnassignedSide: "el microfono {side} no esta asignado",
        reviewChecklist: "Checklist",
        reviewReadyToSave: "Lista para guardar",
        reviewOpenItems: "{count} elementos abiertos",
        reviewDisplays: "Monitores",
        reviewDisplayReady: "Asignaciones completas",
        reviewDisplayMissing: "Asignaciones incompletas",
        reviewMicrophones: "Microfonos",
        reviewMicrophoneReady: "Configuracion alineada",
        reviewMicrophoneMissing: "Revisar asignaciones",
        reviewProvider: "Proveedor",
        reviewAiNotice: "Aviso IA",
        reviewAutostart: "Inicio automatico",
        reviewInitialLanguages: "Flujo de idiomas runtime",
        reviewInitialLanguagesFix: "Revisa los valores runtime guardados",
        reviewInitialLanguagesReady: "La eleccion del idioma se hace en los puestos",
        reviewAutostartEnabled: "Activo",
        reviewAutostartDisabled: "Desactivado",
    reviewAutostartPendingEnable: "Inicio automatico en activacion",
    reviewAutostartPendingDisable: "Inicio automatico en desactivacion",
        autostartUnavailable: "Disponible solo en instalaciones packaged de Windows.",
        autostartEnabledNote: "OnlySpeech se iniciara automaticamente cuando el usuario actual inicie sesion.",
        autostartDisabledNote: "OnlySpeech no se iniciara automaticamente al iniciar sesion.",
    autostartWillEnableOnSave: "El inicio automatico se esta activando.",
    autostartWillDisableOnSave: "El inicio automatico se esta desactivando.",
        reviewAzureTts: "Azure TTS",
        reviewAzureTtsFix: "Aun faltan catalogo o voces A/B",
        reviewAzureTtsReady: "Cobertura A/B lista",
        bothDisplaysAssigned: "Ambos monitores estan asignados.",
        displayUnassignedBadge: "Monitor sin asignar",
        assignStationA: "Asignar al Puesto A",
        assignStationB: "Asignar al Puesto B",
        stationASelected: "Puesto A seleccionado",
        stationBSelected: "Puesto B seleccionado",
        removeAssignment: "Quitar asignacion",
        displayAssignedStatus: "Monitor {id} asignado al lado {side}.",
        displayAssignmentRemoved: "Asignacion del monitor eliminada.",
        displayAssignmentUpdateFailed: "No se pudo actualizar la asignacion del monitor",
        microphonePermissionDenied: "Permiso de microfono denegado: {detail}",
        grantMicrophonePermission: "Concede el permiso de microfono.",
        twoDistinctMicrophonesRequired: "Se necesitan dos microfonos distintos para completar la configuracion.",
        selectOneSharedMicrophone: "Selecciona al menos un microfono para el perfil compartido.",
        demoNeedsNoMicrophones: "El modo demo no requiere microfonos live para el bucle runtime.",
        noMicrophonesDetected: "No se detecto ningun microfono. Usa \\\"Detectar microfonos\\\" para actualizar el inventario.",
        selectMicrophone: "Selecciona microfono",
        monitorUnassigned: "ningun monitor asignado",
        assignedMicrophoneLabel: "Microfono asignado",
        sharedProfileHint: "Perfil compartido: puedes asignar el mismo microfono a ambos puestos.",
        clearMicrophoneAssignmentAria: "Quitar asignacion de microfono del lado {side}",
        clearMicrophoneAssignment: "Quitar asignacion",
        microphoneUpdated: "Microfono del lado {side} actualizado.",
        microphoneRemoved: "Microfono del lado {side} eliminado.",
        microphoneUpdateFailed: "No se pudo actualizar el microfono",
        microphoneRemoveFailed: "No se pudo eliminar el microfono",
        microphoneTestStopping: "Deteniendo...",
        microphoneTestStop: "Detener prueba",
        microphoneTestStart: "Iniciar prueba",
        stationsProbeLabel: "Deteccion de microfonos en curso",
        stationsProbeDetail: "Espera a que termine la deteccion antes de asignar nuevos dispositivos.",
        providerTestLabel: "Prueba del proveedor en curso",
        providerTestDetail: "El proveedor esta procesando la traduccion de muestra.",
        providerSpeechAzureLabel: "Prueba live Azure en curso",
        providerSpeechChatGptLabel: "Enviando audio final-turn",
        providerSpeechAzureDetail: "Azure Speech esta escuchando en el microfono seleccionado.",
        providerSpeechChatGptDetail: "ChatGPT esta procesando el audio final-turn.",
        probeMicrophonesIdle: "Detectar microfonos",
        probeMicrophonesBusy: "Detectando...",
        saveSectionIdle: "Guardar",
        saveSectionBusy: "Guardando...",
        saveAndCloseIdle: "Aplicar y cerrar setup",
        saveAndCloseBusy: "Aplicando y cerrando...",
        providerTestIdle: "Ejecutar prueba del proveedor",
        providerTestBusy: "Prueba del proveedor en curso...",
        azureLiveBusy: "Prueba live Azure en curso...",
        azureLiveStart: "Iniciar prueba live Azure",
        finalTurnStopAndSend: "Detener y enviar turno final",
        finalTurnStart: "Iniciar prueba final-turn",
        finalTurnSending: "Enviando turno final...",
        unnamedMicrophone: "Microfono sin nombre",
        issueMissingDisplayA: "el monitor A no esta asignado",
        issueMissingDisplayB: "el monitor B no esta asignado",
        issueMissingMicrophoneA: "el microfono A no esta asignado",
        issueMissingMicrophoneB: "el microfono B no esta asignado",
        issueMissingSharedMicrophone: "el microfono compartido no esta asignado",
        issueDistinctMicrophonesRequired: "se requieren dos microfonos distintos",
        issueUnsupportedProvider: "el proveedor no esta configurado",
        issueMissingProviderCredentials: "faltan credenciales del proveedor"
      };
      copyByLanguage.fr = {
        ...copyByLanguage.en,
        checklistReadyTitle: "Configuration essentielle complete",
        checklistReadyBody: "Ecrans, microphones et fournisseur sont assignes. Vous pouvez lancer les tests et enregistrer.",
        displayPending: "Ecran a assigner",
        displayUnassignedSide: "l'ecran {side} n'est pas assigne",
        microphonePending: "Microphone a assigner",
        microphoneAssignedToSide: "Assigne au cote {side}",
        microphoneUnassignedSide: "le microphone {side} n'est pas assigne",
        reviewReadyToSave: "Pret a enregistrer",
        reviewOpenItems: "{count} elements ouverts",
        reviewDisplays: "Ecrans",
        reviewDisplayReady: "Affectations completes",
        reviewDisplayMissing: "Affectations incompletes",
        reviewMicrophones: "Microphones",
        reviewMicrophoneReady: "Configuration alignee",
        reviewMicrophoneMissing: "Verifier les affectations",
        reviewProvider: "Fournisseur",
        reviewAiNotice: "Avis IA",
        reviewAutostart: "Demarrage automatique",
        reviewInitialLanguages: "Flux de langue runtime",
        reviewInitialLanguagesFix: "Verifier les valeurs runtime enregistrees",
        reviewInitialLanguagesReady: "Le choix de la langue se fait sur les postes",
        reviewAutostartEnabled: "Actif",
        reviewAutostartDisabled: "Desactive",
    reviewAutostartPendingEnable: "Demarrage automatique en cours d'activation",
    reviewAutostartPendingDisable: "Demarrage automatique en cours de desactivation",
        autostartUnavailable: "Disponible uniquement dans les installations Windows packagees.",
        autostartEnabledNote: "OnlySpeech demarre automatiquement quand l'utilisateur Windows courant ouvre sa session.",
        autostartDisabledNote: "OnlySpeech ne demarre pas automatiquement a l'ouverture de session.",
    autostartWillEnableOnSave: "Le demarrage automatique est en cours d'activation.",
    autostartWillDisableOnSave: "Le demarrage automatique est en cours de desactivation.",
        bothDisplaysAssigned: "Les deux ecrans sont assignes.",
        displayUnassignedBadge: "Ecran non assigne",
        assignStationA: "Assigner au Poste A",
        assignStationB: "Assigner au Poste B",
        stationASelected: "Poste A selectionne",
        stationBSelected: "Poste B selectionne",
        removeAssignment: "Retirer l'affectation",
        displayAssignedStatus: "Ecran {id} assigne au cote {side}.",
        displayAssignmentRemoved: "Affectation de l'ecran retiree.",
        displayAssignmentUpdateFailed: "Impossible de mettre a jour l'affectation de l'ecran",
        microphonePermissionDenied: "Permission micro refusee : {detail}",
        grantMicrophonePermission: "Accordez la permission microphone.",
        twoDistinctMicrophonesRequired: "Deux microphones distincts sont requis pour terminer la configuration.",
        selectOneSharedMicrophone: "Selectionnez au moins un microphone pour le profil partage.",
        demoNeedsNoMicrophones: "Le mode demo n'exige pas de microphones live pour la boucle runtime.",
        noMicrophonesDetected: "Aucun microphone detecte. Utilisez \\\"Detecter les microphones\\\" pour actualiser l'inventaire.",
        selectMicrophone: "Selectionner un microphone",
        monitorUnassigned: "aucun ecran assigne",
        assignedMicrophoneLabel: "Microphone assigne",
        sharedProfileHint: "Profil partage : vous pouvez assigner le meme microphone aux deux postes.",
        clearMicrophoneAssignmentAria: "Retirer l'affectation du microphone cote {side}",
        clearMicrophoneAssignment: "Retirer l'affectation",
        microphoneUpdated: "Microphone du cote {side} mis a jour.",
        microphoneRemoved: "Microphone du cote {side} retire.",
        microphoneUpdateFailed: "Impossible de mettre a jour le microphone",
        microphoneRemoveFailed: "Impossible de retirer le microphone",
        microphoneTestStopping: "Arret...",
        microphoneTestStop: "Arreter le test",
        microphoneTestStart: "Demarrer le test",
        stationsProbeLabel: "Detection des microphones en cours",
        stationsProbeDetail: "Attendez la fin de la detection avant d'assigner de nouveaux peripheriques.",
        providerTestLabel: "Test fournisseur en cours",
        providerTestDetail: "Le fournisseur traite la traduction d'exemple.",
        providerSpeechAzureLabel: "Test live Azure en cours",
        providerSpeechChatGptLabel: "Envoi de l'audio final-turn",
        providerSpeechAzureDetail: "Azure Speech ecoute sur le microphone selectionne.",
        providerSpeechChatGptDetail: "ChatGPT traite l'audio final-turn.",
        probeMicrophonesIdle: "Detecter les microphones",
        probeMicrophonesBusy: "Detection...",
        saveAndCloseIdle: "Appliquer et fermer le setup",
        saveAndCloseBusy: "Application et fermeture...",
        providerTestIdle: "Lancer le test fournisseur",
        providerTestBusy: "Test fournisseur en cours...",
        azureLiveBusy: "Test live Azure en cours...",
        azureLiveStart: "Demarrer le test live Azure",
        finalTurnStopAndSend: "Arreter et envoyer le tour final",
        finalTurnStart: "Demarrer le test final-turn",
        finalTurnSending: "Envoi du tour final...",
        unnamedMicrophone: "Microphone sans nom"
      };
      copyByLanguage.de = {
        ...copyByLanguage.en,
        checklistReadyTitle: "Grundkonfiguration abgeschlossen",
        checklistReadyBody: "Monitore, Mikrofone und Anbieter sind zugewiesen. Sie koennen Tests ausfuehren und speichern.",
        displayPending: "Monitor zuweisen",
        displayUnassignedSide: "Monitor {side} ist nicht zugewiesen",
        microphonePending: "Mikrofon zuweisen",
        microphoneAssignedToSide: "Der Seite {side} zugewiesen",
        microphoneUnassignedSide: "Mikrofon {side} ist nicht zugewiesen",
        reviewReadyToSave: "Bereit zum Speichern",
        reviewOpenItems: "{count} offene Punkte",
        reviewDisplays: "Monitore",
        reviewDisplayReady: "Zuweisungen vollstaendig",
        reviewDisplayMissing: "Zuweisungen unvollstaendig",
        reviewMicrophones: "Mikrofone",
        reviewMicrophoneReady: "Konfiguration abgestimmt",
        reviewMicrophoneMissing: "Zuweisungen pruefen",
        reviewProvider: "Anbieter",
        reviewAiNotice: "KI-Hinweis",
        reviewAutostart: "Automatischer Start",
        reviewInitialLanguages: "Runtime-Sprachfluss",
        reviewInitialLanguagesFix: "Gespeicherte Runtime-Standards pruefen",
        reviewInitialLanguagesReady: "Sprachauswahl erfolgt an den Stationen",
        reviewAutostartEnabled: "Aktiv",
        reviewAutostartDisabled: "Deaktiviert",
    reviewAutostartPendingEnable: "Automatischer Start wird aktiviert",
    reviewAutostartPendingDisable: "Automatischer Start wird deaktiviert",
        autostartUnavailable: "Nur in paketierten Windows-Installationen verfuegbar.",
        autostartEnabledNote: "OnlySpeech startet automatisch, wenn sich der aktuelle Windows-Benutzer anmeldet.",
        autostartDisabledNote: "OnlySpeech startet bei der Anmeldung nicht automatisch.",
    autostartWillEnableOnSave: "Der automatische Start wird aktiviert.",
    autostartWillDisableOnSave: "Der automatische Start wird deaktiviert.",
        bothDisplaysAssigned: "Beide Monitore sind zugewiesen.",
        displayUnassignedBadge: "Monitor nicht zugewiesen",
        assignStationA: "Station A zuweisen",
        assignStationB: "Station B zuweisen",
        stationASelected: "Station A ausgewaehlt",
        stationBSelected: "Station B ausgewaehlt",
        removeAssignment: "Zuweisung entfernen",
        displayAssignedStatus: "Monitor {id} der Seite {side} zugewiesen.",
        displayAssignmentRemoved: "Monitorzuweisung entfernt.",
        displayAssignmentUpdateFailed: "Monitorzuweisung konnte nicht aktualisiert werden",
        microphonePermissionDenied: "Mikrofonberechtigung verweigert: {detail}",
        grantMicrophonePermission: "Erteilen Sie die Mikrofonberechtigung.",
        twoDistinctMicrophonesRequired: "Zum Abschluss der Konfiguration sind zwei unterschiedliche Mikrofone erforderlich.",
        selectOneSharedMicrophone: "Waehlen Sie mindestens ein Mikrofon fuer das gemeinsame Profil.",
        demoNeedsNoMicrophones: "Der Demo-Modus benoetigt keine Live-Mikrofone fuer die Runtime-Schleife.",
        noMicrophonesDetected: "Kein Mikrofon erkannt. Verwenden Sie \\\"Mikrofone erkennen\\\", um das Inventar zu aktualisieren.",
        selectMicrophone: "Mikrofon waehlen",
        monitorUnassigned: "kein Monitor zugewiesen",
        assignedMicrophoneLabel: "Zugewiesenes Mikrofon",
        sharedProfileHint: "Gemeinsames Profil: Dasselbe Mikrofon kann beiden Stationen zugewiesen werden.",
        clearMicrophoneAssignmentAria: "Mikrofonzuweisung fuer Seite {side} entfernen",
        clearMicrophoneAssignment: "Zuweisung entfernen",
        microphoneUpdated: "Mikrofon fuer Seite {side} aktualisiert.",
        microphoneRemoved: "Mikrofon fuer Seite {side} entfernt.",
        microphoneUpdateFailed: "Mikrofon konnte nicht aktualisiert werden",
        microphoneRemoveFailed: "Mikrofon konnte nicht entfernt werden",
        microphoneTestStopping: "Wird gestoppt...",
        microphoneTestStop: "Test stoppen",
        microphoneTestStart: "Test starten",
        stationsProbeLabel: "Mikrofonerkennung laeuft",
        stationsProbeDetail: "Warten Sie mit neuen Zuweisungen, bis die Erkennung abgeschlossen ist.",
        providerTestLabel: "Anbieter-Test laeuft",
        providerTestDetail: "Der Anbieter verarbeitet die Beispieluebersetzung.",
        providerSpeechAzureLabel: "Azure-Live-Test laeuft",
        providerSpeechChatGptLabel: "Final-Turn-Audio wird hochgeladen",
        providerSpeechAzureDetail: "Azure Speech hoert am ausgewaehlten Mikrofon zu.",
        providerSpeechChatGptDetail: "ChatGPT verarbeitet das Final-Turn-Audio.",
        probeMicrophonesIdle: "Mikrofone erkennen",
        probeMicrophonesBusy: "Erkennung laeuft...",
        saveAndCloseIdle: "Setup anwenden und schliessen",
        saveAndCloseBusy: "Wird angewendet und geschlossen...",
        providerTestIdle: "Anbieter-Test ausfuehren",
        providerTestBusy: "Anbieter-Test laeuft...",
        azureLiveBusy: "Azure-Live-Test laeuft...",
        azureLiveStart: "Azure-Live-Test starten",
        finalTurnStopAndSend: "Finalen Turn stoppen und senden",
        finalTurnStart: "Final-Turn-Test starten",
        finalTurnSending: "Finaler Turn wird gesendet...",
        unnamedMicrophone: "Unbenanntes Mikrofon"
      };
      copyByLanguage.zh = {
        ...copyByLanguage.en,
        checklistReadyTitle: "基础配置已完成",
        checklistReadyBody: "显示器、麦克风和服务商已分配。现在可以运行测试并保存。",
        displayPending: "待分配显示器",
        displayUnassignedSide: "显示器 {side} 未分配",
        microphonePending: "待分配麦克风",
        microphoneAssignedToSide: "已分配到 {side} 侧",
        microphoneUnassignedSide: "麦克风 {side} 未分配",
        reviewReadyToSave: "可保存",
        reviewOpenItems: "{count} 个待处理项",
        reviewDisplays: "显示器",
        reviewDisplayReady: "分配完成",
        reviewDisplayMissing: "分配未完成",
        reviewMicrophones: "麦克风",
        reviewMicrophoneReady: "配置已对齐",
        reviewMicrophoneMissing: "请检查分配",
        reviewProvider: "服务商",
        reviewAiNotice: "AI 提示",
        reviewAutostart: "自动启动",
        reviewInitialLanguages: "runtime 语言流程",
        reviewInitialLanguagesFix: "请检查已保存的 runtime 默认值",
        reviewInitialLanguagesReady: "语言选择在工作站上完成",
        reviewAutostartEnabled: "已启用",
        reviewAutostartDisabled: "已禁用",
    reviewAutostartPendingEnable: "正在启用自动启动",
    reviewAutostartPendingDisable: "正在禁用自动启动",
        autostartUnavailable: "仅在打包后的 Windows 安装中可用。",
        autostartEnabledNote: "当前 Windows 用户登录时将自动启动 OnlySpeech。",
        autostartDisabledNote: "登录时不会自动启动 OnlySpeech。",
    autostartWillEnableOnSave: "正在启用自动启动。",
    autostartWillDisableOnSave: "正在禁用自动启动。",
        bothDisplaysAssigned: "两台显示器都已分配。",
        displayUnassignedBadge: "未分配显示器",
        assignStationA: "分配到工作站 A",
        assignStationB: "分配到工作站 B",
        stationASelected: "已选择工作站 A",
        stationBSelected: "已选择工作站 B",
        removeAssignment: "移除分配",
        displayAssignedStatus: "显示器 {id} 已分配到 {side} 侧。",
        displayAssignmentRemoved: "显示器分配已移除。",
        displayAssignmentUpdateFailed: "无法更新显示器分配",
        microphonePermissionDenied: "麦克风权限被拒绝：{detail}",
        grantMicrophonePermission: "请授予麦克风权限。",
        twoDistinctMicrophonesRequired: "完成配置需要两个不同的可选麦克风。",
        selectOneSharedMicrophone: "共享配置至少需要选择一个麦克风。",
        demoNeedsNoMicrophones: "演示模式的 runtime 循环不需要 live 麦克风。",
        noMicrophonesDetected: "未检测到麦克风。请使用“探测麦克风”刷新设备清单。",
        selectMicrophone: "选择麦克风",
        monitorUnassigned: "未分配显示器",
        assignedMicrophoneLabel: "已分配麦克风",
        sharedProfileHint: "共享配置：同一个麦克风可以同时分配给两侧工作站。",
        clearMicrophoneAssignmentAria: "移除 {side} 侧麦克风分配",
        clearMicrophoneAssignment: "移除分配",
        microphoneUpdated: "{side} 侧麦克风已更新。",
        microphoneRemoved: "{side} 侧麦克风已移除。",
        microphoneUpdateFailed: "无法更新麦克风",
        microphoneRemoveFailed: "无法移除麦克风",
        microphoneTestStopping: "正在停止...",
        microphoneTestStop: "停止测试",
        microphoneTestStart: "开始测试",
        stationsProbeLabel: "正在探测麦克风",
        stationsProbeDetail: "请等探测完成后再分配新设备。",
        providerTestLabel: "服务商测试进行中",
        providerTestDetail: "服务商正在处理示例翻译。",
        providerSpeechAzureLabel: "Azure live 测试进行中",
        providerSpeechChatGptLabel: "正在上传 final-turn 音频",
        providerSpeechAzureDetail: "Azure Speech 正在监听所选麦克风。",
        providerSpeechChatGptDetail: "ChatGPT 正在处理 final-turn 音频。",
        probeMicrophonesIdle: "探测麦克风",
        probeMicrophonesBusy: "探测中...",
        saveAndCloseIdle: "应用并关闭 setup",
        saveAndCloseBusy: "正在应用并关闭...",
        providerTestIdle: "运行服务商测试",
        providerTestBusy: "服务商测试进行中...",
        azureLiveBusy: "Azure live 测试进行中...",
        azureLiveStart: "开始 Azure live 测试",
        finalTurnStopAndSend: "停止并发送最终轮次",
        finalTurnStart: "开始 final-turn 测试",
        finalTurnSending: "正在发送最终轮次...",
        unnamedMicrophone: "未命名麦克风"
      };
      let copy = copyByLanguage[wizardUiLanguage] || copyByLanguage.en;
      const sampleTextDefaultsByLanguage = {
        en: {
          providerTranslation: "Hello, this is a translation test.",
          providerPlayback: "Hello, this is a provider speech playback test."
        },
        it: {
          providerTranslation: "Buongiorno, questo e' un test di traduzione.",
          providerPlayback: "Buongiorno, questo e' un test di riproduzione provider."
        },
        es: {
          providerTranslation: "Hola, esta es una prueba de traduccion.",
          providerPlayback: "Hola, esta es una prueba de reproduccion del proveedor."
        },
        fr: {
          providerTranslation: "Bonjour, ceci est un test de traduction.",
          providerPlayback: "Bonjour, ceci est un test de lecture du fournisseur."
        },
        de: {
          providerTranslation: "Hallo, dies ist ein Uebersetzungstest.",
          providerPlayback: "Hallo, dies ist ein Wiedergabetest des Anbieters."
        },
        zh: {
          providerTranslation: "你好，这是一次翻译测试。",
          providerPlayback: "你好，这是一次服务商播放测试。"
        }
      };
      const statusDefaultsByLanguage = {
        en: "Initializing setup wizard.",
        it: "Inizializzazione wizard in corso.",
        es: "Inicializando el asistente de configuracion.",
        fr: "Initialisation de l'assistant de configuration.",
        de: "Setup-Assistent wird initialisiert.",
        zh: "正在初始化设置向导。"
      };
`;
}

